import 'package:pi_hole_client/config/enums.dart';
import 'package:pi_hole_client/data/model/v5/realtime_status.dart' as srv;
import 'package:pi_hole_client/domain/model/metrics/summary.dart' as repo;
import 'package:pi_hole_client/domain/model/metrics/top_clients.dart' as repo;
import 'package:pi_hole_client/domain/model/metrics/top_domains.dart' as repo;
import 'package:pi_hole_client/domain/model/metrics/upstreams.dart' as repo;
import 'package:pi_hole_client/domain/model/realtime_status/realtime_status.dart'
    as repo;

const kSrvGetRealTimeStatus = srv.RealTimeStatus(
  domainsBeingBlocked: 121860,
  dnsQueriesToday: 16,
  adsBlockedToday: 1,
  adsPercentageToday: 6.25,
  uniqueDomains: 11,
  queriesForwarded: 9,
  queriesCached: 6,
  clientsEverSeen: 2,
  uniqueClients: 2,
  dnsQueriesAllTypes: 16,
  replyUnknown: 0,
  replyNodata: 0,
  replyNxDomain: 3,
  replyCname: 0,
  replyIp: 10,
  replyDomain: 3,
  replyRrname: 0,
  replyServfail: 0,
  replyRefused: 0,
  replyNotimp: 0,
  replyOther: 0,
  replyDnssec: 0,
  replyNone: 0,
  replyBlob: 0,
  dnsQueriesAllReplies: 16,
  privacyLevel: 0,
  status: 'enabled',
  gravityLastUpdated: srv.GravityLastUpdated(
    fileExists: true,
    absolute: 1732972589,
    relative: srv.GravityRelativeTime(days: 5, hours: 18, minutes: 14),
  ),
  topQueries: {
    '1.0.26.172.in-addr.arpa': 3,
    '8.8.8.8.in-addr.arpa': 3,
    'github.com': 2,
    'gitlab.com': 1,
    'sample.com': 1,
    'test.com': 1,
    'google.com': 1,
    'google.co.jp': 1,
    'yahoo.co.jp': 1,
    'fix.test.com': 1,
  },
  topAds: {'test.com': 1},
  topSources: {'172.26.0.1': 10, 'localhost|127.0.0.1': 6},
  topSourcesBlocked: {'172.26.0.1': 1},
  forwardDestinations: {
    'blocked|blocked': 6.25,
    'cached|cached': 37.5,
    'other|other': 0,
    'dns.google#53|8.8.8.8#53': 56.25,
  },
  queryTypes: srv.QueryTypes(
    a: 62.5,
    aaaa: 0,
    any: 0,
    srv: 0,
    soa: 0,
    ptr: 37.5,
    txt: 0,
    naptr: 0,
    mx: 0,
    ds: 0,
    rrsig: 0,
    dnskey: 0,
    ns: 0,
    other: 0,
    svcb: 0,
    https: 0,
  ),
);

final kRepoFetchRealTimeStatus = repo.RealtimeStatus(
  summary: repo.Summary(
    domainsBeingBlocked: 121860,
    dnsQueriesToday: 16,
    adsBlockedToday: 1,
    adsPercentageToday: 6.25,
    uniqueDomains: 11,
    queriesForwarded: 9,
    queriesCached: 6,
    clientsEverSeen: 2,
    uniqueClients: 2,
    dnsQueriesAllTypes: 16,
    replyUnknown: 0,
    replyNodata: 0,
    replyNxDomain: 3,
    replyCname: 0,
    replyIp: 10,
    replyDomain: 3,
    replyRrname: 0,
    replyServfail: 0,
    replyRefused: 0,
    replyNotimp: 0,
    replyOther: 0,
    replyDnssec: 0,
    replyNone: 0,
    replyBlob: 0,
    dnsQueriesAllReplies: 16,
    queryTypes: const [
      repo.QueryTypeStat(type: DnsRecordType.a, percentage: 62.5),
      repo.QueryTypeStat(type: DnsRecordType.aaaa, percentage: 0),
      repo.QueryTypeStat(type: DnsRecordType.any, percentage: 0),
      repo.QueryTypeStat(type: DnsRecordType.srv, percentage: 0),
      repo.QueryTypeStat(type: DnsRecordType.soa, percentage: 0),
      repo.QueryTypeStat(type: DnsRecordType.ptr, percentage: 37.5),
      repo.QueryTypeStat(type: DnsRecordType.txt, percentage: 0),
      repo.QueryTypeStat(type: DnsRecordType.naptr, percentage: 0),
      repo.QueryTypeStat(type: DnsRecordType.mx, percentage: 0),
      repo.QueryTypeStat(type: DnsRecordType.ds, percentage: 0),
      repo.QueryTypeStat(type: DnsRecordType.rrsig, percentage: 0),
      repo.QueryTypeStat(type: DnsRecordType.dnskey, percentage: 0),
      repo.QueryTypeStat(type: DnsRecordType.ns, percentage: 0),
      repo.QueryTypeStat(type: DnsRecordType.other, percentage: 0),
      repo.QueryTypeStat(type: DnsRecordType.svcb, percentage: 0),
      repo.QueryTypeStat(type: DnsRecordType.https, percentage: 0),
    ],
  ),
  status: DnsBlockingStatus.enabled,
  privacyLevel: 0,
  topDomains: const repo.TopDomains(
    topQueries: [
      repo.QueryStat(domain: '1.0.26.172.in-addr.arpa', count: 3),
      repo.QueryStat(domain: '8.8.8.8.in-addr.arpa', count: 3),
      repo.QueryStat(domain: 'github.com', count: 2),
      repo.QueryStat(domain: 'gitlab.com', count: 1),
      repo.QueryStat(domain: 'sample.com', count: 1),
      repo.QueryStat(domain: 'test.com', count: 1),
      repo.QueryStat(domain: 'google.com', count: 1),
      repo.QueryStat(domain: 'google.co.jp', count: 1),
      repo.QueryStat(domain: 'yahoo.co.jp', count: 1),
      repo.QueryStat(domain: 'fix.test.com', count: 1),
    ],
    topAds: [repo.QueryStat(domain: 'test.com', count: 1)],
  ),
  topClients: const repo.TopClients(
    topSources: [
      repo.SourceStat(source: '172.26.0.1', count: 10),
      repo.SourceStat(source: 'localhost|127.0.0.1', count: 6),
    ],
    topSourcesBlocked: [repo.SourceStat(source: '172.26.0.1', count: 1)],
  ),
  forwardDestinations: const [
    repo.DestinationStat(destination: 'blocked|blocked', percentage: 6.25),
    repo.DestinationStat(destination: 'cached|cached', percentage: 37.5),
    repo.DestinationStat(destination: 'other|other', percentage: 0),
    repo.DestinationStat(
      destination: 'dns.google#53|8.8.8.8#53',
      percentage: 56.25,
    ),
  ],
);
