# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: tsutsu3.Pi-hole-client
PackageVersion: 1.4.0
InstallerType: inno
InstallModes:
- silent
InstallerSwitches:
  Silent: /VERYSILENT /Tasks="desktopicon"
  SilentWithProgress: /SILENT /Tasks="desktopicon"
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tsutsu3/pi-hole-client/releases/download/1.4.0_(43)/PiHoleClient_1.4.0_Windows_x64.exe
  InstallerSha256: F625F41B8D2361A743AC5ABB5515CD60357C1D208D9A197862813F3DFDCAE85F
ManifestType: installer
ManifestVersion: 1.9.0
