# Created using wingetcreate 1.10.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: tsutsu3.Pi-hole-client
PackageVersion: 1.5.0
InstallerType: inno
InstallModes:
- silent
InstallerSwitches:
  Silent: /VERYSILENT /Tasks="desktopicon"
  SilentWithProgress: /SILENT /Tasks="desktopicon"
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tsutsu3/pi-hole-client/releases/download/1.5.0_(55)/PiHoleClient_1.5.0_Windows_x64.exe
  InstallerSha256: 1834790555C644166F168231430A6D5E55BF0072A6FFD8430B16EB35C136C9D8
ManifestType: installer
ManifestVersion: 1.10.0
