engines:
  flutter:
    enabled: true

build:
  before:
    - flutter pub get
    - flutter pub run build_runner build --delete-conflicting-outputs

exclude_paths:
  - test/**
  - lib/**/*.g.dart
  - lib/**/*.freezed.dart
  - lib/l10n/generated/**
  - lib/screens/settings/about/about.dart
  - .github/**
  - .vscode/**
  - android/**
  - assets/**
  - debian/**
  - docs/**
  - ios/**
  - linux/**
  - macos/**
  - mock_api_server/**
  - windows/**
  - winget/**
  - CHANGELOG.md
