targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/domain/**/*.dart
            - lib/data/**/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/domain/**/*.dart
            - lib/data/**/*.dart
