ignore:
  - "lib/ui/settings/about/about.dart"
  - "lib/**/*.g.dart"
  - "lib/**/*.freezed.dart"
  - "lib/ui/core/l10n/generated/**"
  - "lib/data/services/api/generated/**"
  - "mock_api_server/**"
  - "tools/**"
