// Mocks generated by Mockito 5.4.6 from annotations
// in pi_hole_client/test/widgets/helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i13;

import 'package:command_it/command_it.dart' as _i3;
import 'package:device_info_plus/device_info_plus.dart' as _i10;
import 'package:flutter/material.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:package_info_plus/package_info_plus.dart' as _i9;
import 'package:pi_hole_client/config/enums.dart' as _i7;
import 'package:pi_hole_client/config/query_status.dart' as _i16;
import 'package:pi_hole_client/data/model/local/app_db_data.dart' as _i12;
import 'package:pi_hole_client/data/repositories/api/interfaces/actions_respository.dart'
    as _i39;
import 'package:pi_hole_client/data/repositories/api/interfaces/dns_repository.dart'
    as _i25;
import 'package:pi_hole_client/data/repositories/api/interfaces/domain_repository.dart'
    as _i22;
import 'package:pi_hole_client/data/repositories/api/interfaces/ftl_repository.dart'
    as _i26;
import 'package:pi_hole_client/data/repositories/api/interfaces/metrics_repository.dart'
    as _i21;
import 'package:pi_hole_client/data/repositories/api/interfaces/realtime_status_repository.dart'
    as _i24;
import 'package:pi_hole_client/domain/model/app/app_log.dart' as _i8;
import 'package:pi_hole_client/domain/model/client/managed_client.dart' as _i29;
import 'package:pi_hole_client/domain/model/domain/domain.dart' as _i20;
import 'package:pi_hole_client/domain/model/ftl/message.dart' as _i38;
import 'package:pi_hole_client/domain/model/group/group.dart' as _i34;
import 'package:pi_hole_client/domain/model/list/adlist.dart' as _i36;
import 'package:pi_hole_client/domain/model/local_dns/local_dns.dart' as _i31;
import 'package:pi_hole_client/domain/model/metrics/queries.dart' as _i18;
import 'package:pi_hole_client/domain/model/network/network.dart' as _i32;
import 'package:pi_hole_client/domain/model/server/server.dart' as _i15;
import 'package:pi_hole_client/ui/core/themes/theme.dart' as _i2;
import 'package:pi_hole_client/ui/core/view_models/app_config_viewmodel.dart'
    as _i4;
import 'package:pi_hole_client/ui/settings/server_settings/adlists/view_models/gravity_update_viewmodel.dart'
    as _i37;
import 'package:pi_hole_client/ui/core/view_models/local_dns_viewmodel.dart'
    as _i30;
import 'package:pi_hole_client/ui/core/view_models/servers_viewmodel.dart'
    as _i14;
import 'package:pi_hole_client/ui/core/view_models/status_viewmodel.dart' as _i23;
import 'package:pi_hole_client/ui/domains/view_models/domains_viewmodel.dart'
    as _i27;
import 'package:pi_hole_client/ui/logs/view_models/logs_viewmodel.dart' as _i17;
import 'package:pi_hole_client/ui/settings/server_settings/adlists/view_models/adlists_viewmodel.dart'
    as _i35;
import 'package:pi_hole_client/ui/settings/server_settings/widgets/group_client/view_models/clients_viewmodel.dart'
    as _i28;
import 'package:pi_hole_client/ui/settings/server_settings/widgets/group_client/view_models/groups_viewmodel.dart'
    as _i33;
import 'package:result_dart/result_dart.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppColors_0 extends _i1.SmartFake implements _i2.AppColors {
  _FakeAppColors_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommand_1<TParam, TResult> extends _i1.SmartFake
    implements _i3.Command<TParam, TResult> {
  _FakeCommand_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppConfigViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppConfigViewModel extends _i1.Mock
    implements _i4.AppConfigViewModel {
  MockAppConfigViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppColors get colors =>
      (super.noSuchMethod(
            Invocation.getter(#colors),
            returnValue: _FakeAppColors_0(this, Invocation.getter(#colors)),
          )
          as _i2.AppColors);

  @override
  bool get showingSnackbar =>
      (super.noSuchMethod(
            Invocation.getter(#showingSnackbar),
            returnValue: false,
          )
          as bool);

  @override
  int get selectedTab =>
      (super.noSuchMethod(Invocation.getter(#selectedTab), returnValue: 0)
          as int);

  @override
  _i5.ThemeMode get selectedTheme =>
      (super.noSuchMethod(
            Invocation.getter(#selectedTheme),
            returnValue: _i5.ThemeMode.system,
          )
          as _i5.ThemeMode);

  @override
  String get selectedLanguage =>
      (super.noSuchMethod(
            Invocation.getter(#selectedLanguage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#selectedLanguage),
            ),
          )
          as String);

  @override
  _i7.AppThemeMode get appThemeMode =>
      (super.noSuchMethod(
            Invocation.getter(#appThemeMode),
            returnValue: _i7.AppThemeMode.system,
          )
          as _i7.AppThemeMode);

  @override
  int get selectedLanguageNumber =>
      (super.noSuchMethod(
            Invocation.getter(#selectedLanguageNumber),
            returnValue: 0,
          )
          as int);

  @override
  bool get reducedDataCharts =>
      (super.noSuchMethod(
            Invocation.getter(#reducedDataCharts),
            returnValue: false,
          )
          as bool);

  @override
  double get logsPerQuery =>
      (super.noSuchMethod(Invocation.getter(#logsPerQuery), returnValue: 0.0)
          as double);

  @override
  bool get biometricsSupport =>
      (super.noSuchMethod(
            Invocation.getter(#biometricsSupport),
            returnValue: false,
          )
          as bool);

  @override
  bool get useBiometrics =>
      (super.noSuchMethod(Invocation.getter(#useBiometrics), returnValue: false)
          as bool);

  @override
  bool get appUnlocked =>
      (super.noSuchMethod(Invocation.getter(#appUnlocked), returnValue: false)
          as bool);

  @override
  bool get validVibrator =>
      (super.noSuchMethod(Invocation.getter(#validVibrator), returnValue: false)
          as bool);

  @override
  bool get importantInfoReaden =>
      (super.noSuchMethod(
            Invocation.getter(#importantInfoReaden),
            returnValue: false,
          )
          as bool);

  @override
  bool get hideZeroValues =>
      (super.noSuchMethod(
            Invocation.getter(#hideZeroValues),
            returnValue: false,
          )
          as bool);

  @override
  bool get loadingAnimation =>
      (super.noSuchMethod(
            Invocation.getter(#loadingAnimation),
            returnValue: false,
          )
          as bool);

  @override
  _i7.StatisticsVisualizationMode get statisticsVisualizationMode =>
      (super.noSuchMethod(
            Invocation.getter(#statisticsVisualizationMode),
            returnValue: _i7.StatisticsVisualizationMode.list,
          )
          as _i7.StatisticsVisualizationMode);

  @override
  _i7.HomeVisualizationMode get homeVisualizationMode =>
      (super.noSuchMethod(
            Invocation.getter(#homeVisualizationMode),
            returnValue: _i7.HomeVisualizationMode.lineArea,
          )
          as _i7.HomeVisualizationMode);

  @override
  bool get sendCrashReports =>
      (super.noSuchMethod(
            Invocation.getter(#sendCrashReports),
            returnValue: false,
          )
          as bool);

  @override
  List<_i8.AppLog> get logs =>
      (super.noSuchMethod(Invocation.getter(#logs), returnValue: <_i8.AppLog>[])
          as List<_i8.AppLog>);

  @override
  int get logAutoRefreshTime =>
      (super.noSuchMethod(
            Invocation.getter(#logAutoRefreshTime),
            returnValue: 0,
          )
          as int);

  @override
  bool get liveLog =>
      (super.noSuchMethod(Invocation.getter(#liveLog), returnValue: false)
          as bool);

  @override
  bool get isLivelogPaused =>
      (super.noSuchMethod(
            Invocation.getter(#isLivelogPaused),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setShowingSnackbar(bool? status) => super.noSuchMethod(
    Invocation.method(#setShowingSnackbar, [status]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedTab(int? selectedTab) => super.noSuchMethod(
    Invocation.method(#setSelectedTab, [selectedTab]),
    returnValueForMissingStub: null,
  );

  @override
  void setAppInfo(_i9.PackageInfo? appInfo) => super.noSuchMethod(
    Invocation.method(#setAppInfo, [appInfo]),
    returnValueForMissingStub: null,
  );

  @override
  void setAndroidInfo(_i10.AndroidDeviceInfo? deviceInfo) => super.noSuchMethod(
    Invocation.method(#setAndroidInfo, [deviceInfo]),
    returnValueForMissingStub: null,
  );

  @override
  void setIosInfo(_i10.IosDeviceInfo? deviceInfo) => super.noSuchMethod(
    Invocation.method(#setIosInfo, [deviceInfo]),
    returnValueForMissingStub: null,
  );

  @override
  void setBiometricsSupport(bool? isSupported) => super.noSuchMethod(
    Invocation.method(#setBiometricsSupport, [isSupported]),
    returnValueForMissingStub: null,
  );

  @override
  void setAppUnlocked(bool? status) => super.noSuchMethod(
    Invocation.method(#setAppUnlocked, [status]),
    returnValueForMissingStub: null,
  );

  @override
  void setValidVibrator(bool? valid) => super.noSuchMethod(
    Invocation.method(#setValidVibrator, [valid]),
    returnValueForMissingStub: null,
  );

  @override
  void addLog(_i8.AppLog? log) => super.noSuchMethod(
    Invocation.method(#addLog, [log]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedSettingsScreen({required int? screen, bool? notify}) =>
      super.noSuchMethod(
        Invocation.method(#setSelectedSettingsScreen, [], {
          #screen: screen,
          #notify: notify,
        }),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<bool> setUseBiometrics(bool? biometrics) =>
      (super.noSuchMethod(
            Invocation.method(#setUseBiometrics, [biometrics]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setImportantInfoReaden(bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#setImportantInfoReaden, [status]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setPassCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#setPassCode, [code]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setAutoRefreshTime(int? seconds) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoRefreshTime, [seconds]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setLogsPerQuery(double? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLogsPerQuery, [time]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setSendCrashReports(bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#setSendCrashReports, [status]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setLogAutoRefreshTime(int? seconds) =>
      (super.noSuchMethod(
            Invocation.method(#setLogAutoRefreshTime, [seconds]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setLiveLog(bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#setLiveLog, [status]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setLivelogPaused(bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#setLivelogPaused, [status]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  void saveFromDb(_i12.AppDbData? dbData) => super.noSuchMethod(
    Invocation.method(#saveFromDb, [dbData]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<bool> setReducedDataCharts(bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#setReducedDataCharts, [status]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setHideZeroValues(bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#setHideZeroValues, [status]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setShowLoadingAnimation(bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#setShowLoadingAnimation, [status]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setSelectedTheme(_i7.AppThemeMode? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedTheme, [value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setSelectedLanguage(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedLanguage, [value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setStatisticsVisualizationMode(
    _i7.StatisticsVisualizationMode? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setStatisticsVisualizationMode, [value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setHomeVisualizationMode(
    _i7.HomeVisualizationMode? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setHomeVisualizationMode, [value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> restoreAppConfig() =>
      (super.noSuchMethod(
            Invocation.method(#restoreAppConfig, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ServersViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockServersViewModel extends _i1.Mock implements _i14.ServersViewModel {
  MockServersViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppColors get colors =>
      (super.noSuchMethod(
            Invocation.getter(#colors),
            returnValue: _FakeAppColors_0(this, Invocation.getter(#colors)),
          )
          as _i2.AppColors);

  @override
  List<_i15.Server> get getServersList =>
      (super.noSuchMethod(
            Invocation.getter(#getServersList),
            returnValue: <_i15.Server>[],
          )
          as List<_i15.Server>);

  @override
  bool get unverifiedBannerDismissed =>
      (super.noSuchMethod(
            Invocation.getter(#unverifiedBannerDismissed),
            returnValue: false,
          )
          as bool);

  @override
  List<_i15.Server> get serversWithUnverifiedCertificates =>
      (super.noSuchMethod(
            Invocation.getter(#serversWithUnverifiedCertificates),
            returnValue: <_i15.Server>[],
          )
          as List<_i15.Server>);

  @override
  int get numShown =>
      (super.noSuchMethod(Invocation.getter(#numShown), returnValue: 0) as int);

  @override
  List<_i16.QueryStatus> get queryStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#queryStatuses),
            returnValue: <_i16.QueryStatus>[],
          )
          as List<_i16.QueryStatus>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void update(_i4.AppConfigViewModel? provider) => super.noSuchMethod(
    Invocation.method(#update, [provider]),
    returnValueForMissingStub: null,
  );

  @override
  void setConnectingServer(_i15.Server? server) => super.noSuchMethod(
    Invocation.method(#setConnectingServer, [server]),
    returnValueForMissingStub: null,
  );

  @override
  void clearConnectingServer() => super.noSuchMethod(
    Invocation.method(#clearConnectingServer, []),
    returnValueForMissingStub: null,
  );

  @override
  void setUnverifiedBannerDismissed(bool? dismissed) => super.noSuchMethod(
    Invocation.method(#setUnverifiedBannerDismissed, [dismissed]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.QueryStatus? getQueryStatus(String? key) =>
      (super.noSuchMethod(Invocation.method(#getQueryStatus, [key]))
          as _i16.QueryStatus?);

  @override
  _i16.QueryStatus? findQueryStatus(String? key) =>
      (super.noSuchMethod(Invocation.method(#findQueryStatus, [key]))
          as _i16.QueryStatus?);

  @override
  _i11.Future<bool> addServer(_i15.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#addServer, [server]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> editServer(_i15.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#editServer, [server]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> removeServer(String? serverAddress) =>
      (super.noSuchMethod(
            Invocation.method(#removeServer, [serverAddress]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setDefaultServer(_i15.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultServer, [server]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<dynamic> saveFromDb(List<_i15.Server>? servers) =>
      (super.noSuchMethod(
            Invocation.method(#saveFromDb, [servers]),
            returnValue: _i11.Future<dynamic>.value(),
          )
          as _i11.Future<dynamic>);

  @override
  _i11.FutureOr<Map<String, dynamic>> checkUrlExists(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#checkUrlExists, [url]),
            returnValue: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i11.FutureOr<Map<String, dynamic>>);

  @override
  void setselectedServer({required _i15.Server? server, bool? toHomeTab}) =>
      super.noSuchMethod(
        Invocation.method(#setselectedServer, [], {
          #server: server,
          #toHomeTab: toHomeTab,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void updateselectedServerStatus(bool? enabled) => super.noSuchMethod(
    Invocation.method(#updateselectedServerStatus, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<bool> deleteDbData() =>
      (super.noSuchMethod(
            Invocation.method(#deleteDbData, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> resetSelectedServer() =>
      (super.noSuchMethod(
            Invocation.method(#resetSelectedServer, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LogsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogsViewModel extends _i1.Mock implements _i17.LogsViewModel {
  MockLogsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiVersion =>
      (super.noSuchMethod(
            Invocation.getter(#apiVersion),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#apiVersion),
            ),
          )
          as String);

  @override
  List<int> get statusAllowedAndRetried =>
      (super.noSuchMethod(
            Invocation.getter(#statusAllowedAndRetried),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  List<int> get defaultSelected =>
      (super.noSuchMethod(
            Invocation.getter(#defaultSelected),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  List<int> get statusSelected =>
      (super.noSuchMethod(
            Invocation.getter(#statusSelected),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  String get statusSelectedString =>
      (super.noSuchMethod(
            Invocation.getter(#statusSelectedString),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#statusSelectedString),
            ),
          )
          as String);

  @override
  List<String> get totalClients =>
      (super.noSuchMethod(
            Invocation.getter(#totalClients),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get selectedClients =>
      (super.noSuchMethod(
            Invocation.getter(#selectedClients),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i7.RequestStatus get requestStatus =>
      (super.noSuchMethod(
            Invocation.getter(#requestStatus),
            returnValue: _i7.RequestStatus.all,
          )
          as _i7.RequestStatus);

  @override
  Set<_i7.QueryStatusType> get selectedStatusTypes =>
      (super.noSuchMethod(
            Invocation.getter(#selectedStatusTypes),
            returnValue: <_i7.QueryStatusType>{},
          )
          as Set<_i7.QueryStatusType>);

  @override
  Set<_i7.QueryStatusType> get allowedAndRetriedStatusTypes =>
      (super.noSuchMethod(
            Invocation.getter(#allowedAndRetriedStatusTypes),
            returnValue: <_i7.QueryStatusType>{},
          )
          as Set<_i7.QueryStatusType>);

  @override
  Set<_i7.QueryStatusType> get allStatusTypes =>
      (super.noSuchMethod(
            Invocation.getter(#allStatusTypes),
            returnValue: <_i7.QueryStatusType>{},
          )
          as Set<_i7.QueryStatusType>);

  @override
  List<_i18.Log> get logsList =>
      (super.noSuchMethod(
            Invocation.getter(#logsList),
            returnValue: <_i18.Log>[],
          )
          as List<_i18.Log>);

  @override
  _i7.LoadStatus get loadStatus =>
      (super.noSuchMethod(
            Invocation.getter(#loadStatus),
            returnValue: _i7.LoadStatus.loading,
          )
          as _i7.LoadStatus);

  @override
  int get sortStatus =>
      (super.noSuchMethod(Invocation.getter(#sortStatus), returnValue: 0)
          as int);

  @override
  bool get isLoadingMore =>
      (super.noSuchMethod(Invocation.getter(#isLoadingMore), returnValue: false)
          as bool);

  @override
  String get searchText =>
      (super.noSuchMethod(
            Invocation.getter(#searchText),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#searchText),
            ),
          )
          as String);

  @override
  double get logsPerQuery =>
      (super.noSuchMethod(Invocation.getter(#logsPerQuery), returnValue: 0.0)
          as double);

  @override
  bool get screenActive =>
      (super.noSuchMethod(Invocation.getter(#screenActive), returnValue: false)
          as bool);

  @override
  bool get isFiltering =>
      (super.noSuchMethod(Invocation.getter(#isFiltering), returnValue: false)
          as bool);

  @override
  List<_i18.Log> get logsListDisplay =>
      (super.noSuchMethod(
            Invocation.getter(#logsListDisplay),
            returnValue: <_i18.Log>[],
          )
          as List<_i18.Log>);

  @override
  bool get hasActiveChips =>
      (super.noSuchMethod(
            Invocation.getter(#hasActiveChips),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void refreshClients() => super.noSuchMethod(
    Invocation.method(#refreshClients, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i19.ResultDart<_i20.Domain, Exception>> addDomainToList({
    required String? list,
    required String? domain,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addDomainToList, [], {
              #list: list,
              #domain: domain,
            }),
            returnValue:
                _i11.Future<_i19.ResultDart<_i20.Domain, Exception>>.value(
                  _i6.dummyValue<_i19.ResultDart<_i20.Domain, Exception>>(
                    this,
                    Invocation.method(#addDomainToList, [], {
                      #list: list,
                      #domain: domain,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i19.ResultDart<_i20.Domain, Exception>>);

  @override
  void setStatusSelected(List<int>? values) => super.noSuchMethod(
    Invocation.method(#setStatusSelected, [values]),
    returnValueForMissingStub: null,
  );

  @override
  void setStartTime(DateTime? value) => super.noSuchMethod(
    Invocation.method(#setStartTime, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setEndTime(DateTime? value) => super.noSuchMethod(
    Invocation.method(#setEndTime, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void resetFilters() => super.noSuchMethod(
    Invocation.method(#resetFilters, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetTime() => super.noSuchMethod(
    Invocation.method(#resetTime, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetStatus() => super.noSuchMethod(
    Invocation.method(#resetStatus, []),
    returnValueForMissingStub: null,
  );

  @override
  void setClients(List<String>? clients) => super.noSuchMethod(
    Invocation.method(#setClients, [clients]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedClients(List<String>? selectedClients) => super.noSuchMethod(
    Invocation.method(#setSelectedClients, [selectedClients]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedDomain(String? domain) => super.noSuchMethod(
    Invocation.method(#setSelectedDomain, [domain]),
    returnValueForMissingStub: null,
  );

  @override
  void resetClients() => super.noSuchMethod(
    Invocation.method(#resetClients, []),
    returnValueForMissingStub: null,
  );

  @override
  void setRequestStatus(_i7.RequestStatus? status) => super.noSuchMethod(
    Invocation.method(#setRequestStatus, [status]),
    returnValueForMissingStub: null,
  );

  @override
  bool isAllowedOrRetried(_i7.QueryStatusType? status) =>
      (super.noSuchMethod(
            Invocation.method(#isAllowedOrRetried, [status]),
            returnValue: false,
          )
          as bool);

  @override
  void update({
    _i21.MetricsRepository? metricsRepository,
    _i22.DomainRepository? domainRepository,
    String? apiVersion,
    List<String>? topClientNames,
    _i13.VoidCallback? onRefreshClients,
  }) => super.noSuchMethod(
    Invocation.method(#update, [], {
      #metricsRepository: metricsRepository,
      #domainRepository: domainRepository,
      #apiVersion: apiVersion,
      #topClientNames: topClientNames,
      #onRefreshClients: onRefreshClients,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void initScreen({required double? logsPerQuery}) => super.noSuchMethod(
    Invocation.method(#initScreen, [], {#logsPerQuery: logsPerQuery}),
    returnValueForMissingStub: null,
  );

  @override
  void resumeScreen() => super.noSuchMethod(
    Invocation.method(#resumeScreen, []),
    returnValueForMissingStub: null,
  );

  @override
  void disposeScreen() => super.noSuchMethod(
    Invocation.method(#disposeScreen, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> initializeLoad() =>
      (super.noSuchMethod(
            Invocation.method(#initializeLoad, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> applyFilterAndLoad({
    DateTime? inStartTime,
    DateTime? inEndTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#applyFilterAndLoad, [], {
              #inStartTime: inStartTime,
              #inEndTime: inEndTime,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void resetLogs() => super.noSuchMethod(
    Invocation.method(#resetLogs, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> enqueueLoadMore() =>
      (super.noSuchMethod(
            Invocation.method(#enqueueLoadMore, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void setSelectedLog(_i18.Log? log) => super.noSuchMethod(
    Invocation.method(#setSelectedLog, [log]),
    returnValueForMissingStub: null,
  );

  @override
  void setSearchText(String? text) => super.noSuchMethod(
    Invocation.method(#setSearchText, [text]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSortStatus(int? value) => super.noSuchMethod(
    Invocation.method(#updateSortStatus, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void configureLive({
    required bool? liveLogEnabled,
    required bool? isLivelogPaused,
    required bool? isOnLogsTab,
    required int? logAutoRefreshTime,
  }) => super.noSuchMethod(
    Invocation.method(#configureLive, [], {
      #liveLogEnabled: liveLogEnabled,
      #isLivelogPaused: isLivelogPaused,
      #isOnLogsTab: isOnLogsTab,
      #logAutoRefreshTime: logAutoRefreshTime,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StatusViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatusViewModel extends _i1.Mock implements _i23.StatusViewModel {
  MockStatusViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.LoadStatus get getServerStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getServerStatus),
            returnValue: _i7.LoadStatus.loading,
          )
          as _i7.LoadStatus);

  @override
  bool get isServerLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isServerLoading),
            returnValue: false,
          )
          as bool);

  @override
  _i7.LoadStatus get getStatusLoading =>
      (super.noSuchMethod(
            Invocation.getter(#getStatusLoading),
            returnValue: _i7.LoadStatus.loading,
          )
          as _i7.LoadStatus);

  @override
  _i7.LoadStatus get getOvertimeDataLoadStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getOvertimeDataLoadStatus),
            returnValue: _i7.LoadStatus.loading,
          )
          as _i7.LoadStatus);

  @override
  bool get isAutoRefreshRunning =>
      (super.noSuchMethod(
            Invocation.getter(#isAutoRefreshRunning),
            returnValue: false,
          )
          as bool);

  @override
  List<String> get topClientNames =>
      (super.noSuchMethod(
            Invocation.getter(#topClientNames),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void update({
    _i24.RealtimeStatusRepository? realtimeStatusRepository,
    _i21.MetricsRepository? metricsRepository,
    _i25.DnsRepository? dnsRepository,
    _i26.FtlRepository? ftlRepository,
    String? apiVersion,
    String? selectedServerAddress,
    String? selectedServerAlias,
    bool? isConnecting = false,
    int? autoRefreshTime,
    void Function(bool)? onUpdateServerStatus,
  }) => super.noSuchMethod(
    Invocation.method(#update, [], {
      #realtimeStatusRepository: realtimeStatusRepository,
      #metricsRepository: metricsRepository,
      #dnsRepository: dnsRepository,
      #ftlRepository: ftlRepository,
      #apiVersion: apiVersion,
      #selectedServerAddress: selectedServerAddress,
      #selectedServerAlias: selectedServerAlias,
      #isConnecting: isConnecting,
      #autoRefreshTime: autoRefreshTime,
      #onUpdateServerStatus: onUpdateServerStatus,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void setServerStatus(_i7.LoadStatus? status) => super.noSuchMethod(
    Invocation.method(#setServerStatus, [status]),
    returnValueForMissingStub: null,
  );

  @override
  void startAutoRefresh({
    bool? runImmediately = true,
    bool? isDelay = false,
    bool? showLoadingIndicator = true,
  }) => super.noSuchMethod(
    Invocation.method(#startAutoRefresh, [], {
      #runImmediately: runImmediately,
      #isDelay: isDelay,
      #showLoadingIndicator: showLoadingIndicator,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<bool> refreshOnce() =>
      (super.noSuchMethod(
            Invocation.method(#refreshOnce, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  void stopAutoRefresh({bool? showLoadingIndicator = true}) =>
      super.noSuchMethod(
        Invocation.method(#stopAutoRefresh, [], {
          #showLoadingIndicator: showLoadingIndicator,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DomainsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockDomainsViewModel extends _i1.Mock implements _i27.DomainsViewModel {
  MockDomainsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Command<void, void> get loadDomains =>
      (super.noSuchMethod(
            Invocation.getter(#loadDomains),
            returnValue: _FakeCommand_1<void, void>(
              this,
              Invocation.getter(#loadDomains),
            ),
          )
          as _i3.Command<void, void>);

  @override
  _i3.Command<_i20.Domain, void> get deleteDomain =>
      (super.noSuchMethod(
            Invocation.getter(#deleteDomain),
            returnValue: _FakeCommand_1<_i20.Domain, void>(
              this,
              Invocation.getter(#deleteDomain),
            ),
          )
          as _i3.Command<_i20.Domain, void>);

  @override
  _i3.Command<({String domain, _i7.DomainKind kind, _i7.DomainType type}), void>
  get addDomain =>
      (super.noSuchMethod(
            Invocation.getter(#addDomain),
            returnValue:
                _FakeCommand_1<
                  ({String domain, _i7.DomainKind kind, _i7.DomainType type}),
                  void
                >(this, Invocation.getter(#addDomain)),
          )
          as _i3.Command<
            ({String domain, _i7.DomainKind kind, _i7.DomainType type}),
            void
          >);

  @override
  _i3.Command<_i20.Domain, void> get updateDomain =>
      (super.noSuchMethod(
            Invocation.getter(#updateDomain),
            returnValue: _FakeCommand_1<_i20.Domain, void>(
              this,
              Invocation.getter(#updateDomain),
            ),
          )
          as _i3.Command<_i20.Domain, void>);

  @override
  List<_i20.Domain> get whitelistDomains =>
      (super.noSuchMethod(
            Invocation.getter(#whitelistDomains),
            returnValue: <_i20.Domain>[],
          )
          as List<_i20.Domain>);

  @override
  List<_i20.Domain> get blacklistDomains =>
      (super.noSuchMethod(
            Invocation.getter(#blacklistDomains),
            returnValue: <_i20.Domain>[],
          )
          as List<_i20.Domain>);

  @override
  List<_i20.Domain> get filteredWhitelistDomains =>
      (super.noSuchMethod(
            Invocation.getter(#filteredWhitelistDomains),
            returnValue: <_i20.Domain>[],
          )
          as List<_i20.Domain>);

  @override
  List<_i20.Domain> get filteredBlacklistDomains =>
      (super.noSuchMethod(
            Invocation.getter(#filteredBlacklistDomains),
            returnValue: <_i20.Domain>[],
          )
          as List<_i20.Domain>);

  @override
  String get searchTerm =>
      (super.noSuchMethod(
            Invocation.getter(#searchTerm),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#searchTerm),
            ),
          )
          as String);

  @override
  bool get searchMode =>
      (super.noSuchMethod(Invocation.getter(#searchMode), returnValue: false)
          as bool);

  @override
  _i7.LoadStatus get loadingStatus =>
      (super.noSuchMethod(
            Invocation.getter(#loadingStatus),
            returnValue: _i7.LoadStatus.loading,
          )
          as _i7.LoadStatus);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setSelectedTab(int? tab) => super.noSuchMethod(
    Invocation.method(#setSelectedTab, [tab]),
    returnValueForMissingStub: null,
  );

  @override
  void setSearchMode(bool? value) => super.noSuchMethod(
    Invocation.method(#setSearchMode, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setGroupFilter(int? groupId) => super.noSuchMethod(
    Invocation.method(#setGroupFilter, [groupId]),
    returnValueForMissingStub: null,
  );

  @override
  void clearGroupFilter() => super.noSuchMethod(
    Invocation.method(#clearGroupFilter, []),
    returnValueForMissingStub: null,
  );

  @override
  void onSearch(String? value) => super.noSuchMethod(
    Invocation.method(#onSearch, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ClientsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientsViewModel extends _i1.Mock implements _i28.ClientsViewModel {
  MockClientsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Command<void, void> get loadClients =>
      (super.noSuchMethod(
            Invocation.getter(#loadClients),
            returnValue: _FakeCommand_1<void, void>(
              this,
              Invocation.getter(#loadClients),
            ),
          )
          as _i3.Command<void, void>);

  @override
  _i3.Command<({String client, String? comment, List<int>? groups}), void>
  get addClient =>
      (super.noSuchMethod(
            Invocation.getter(#addClient),
            returnValue:
                _FakeCommand_1<
                  ({String client, String? comment, List<int>? groups}),
                  void
                >(this, Invocation.getter(#addClient)),
          )
          as _i3.Command<
            ({String client, String? comment, List<int>? groups}),
            void
          >);

  @override
  _i3.Command<({String client, String? comment, List<int>? groups}), void>
  get updateClient =>
      (super.noSuchMethod(
            Invocation.getter(#updateClient),
            returnValue:
                _FakeCommand_1<
                  ({String client, String? comment, List<int>? groups}),
                  void
                >(this, Invocation.getter(#updateClient)),
          )
          as _i3.Command<
            ({String client, String? comment, List<int>? groups}),
            void
          >);

  @override
  _i3.Command<_i29.ManagedClient, void> get deleteClient =>
      (super.noSuchMethod(
            Invocation.getter(#deleteClient),
            returnValue: _FakeCommand_1<_i29.ManagedClient, void>(
              this,
              Invocation.getter(#deleteClient),
            ),
          )
          as _i3.Command<_i29.ManagedClient, void>);

  @override
  List<_i29.ManagedClient> get clients =>
      (super.noSuchMethod(
            Invocation.getter(#clients),
            returnValue: <_i29.ManagedClient>[],
          )
          as List<_i29.ManagedClient>);

  @override
  List<_i29.ManagedClient> get filteredClients =>
      (super.noSuchMethod(
            Invocation.getter(#filteredClients),
            returnValue: <_i29.ManagedClient>[],
          )
          as List<_i29.ManagedClient>);

  @override
  String get searchTerm =>
      (super.noSuchMethod(
            Invocation.getter(#searchTerm),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#searchTerm),
            ),
          )
          as String);

  @override
  bool get searchMode =>
      (super.noSuchMethod(Invocation.getter(#searchMode), returnValue: false)
          as bool);

  @override
  _i7.LoadStatus get loadingStatus =>
      (super.noSuchMethod(
            Invocation.getter(#loadingStatus),
            returnValue: _i7.LoadStatus.loading,
          )
          as _i7.LoadStatus);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void updateMacLookup(Map<String, String>? ipToMac) => super.noSuchMethod(
    Invocation.method(#updateMacLookup, [ipToMac]),
    returnValueForMissingStub: null,
  );

  @override
  void updateGroupLookup(Map<int, String>? groupNames) => super.noSuchMethod(
    Invocation.method(#updateGroupLookup, [groupNames]),
    returnValueForMissingStub: null,
  );

  @override
  void setSearchMode(bool? value) => super.noSuchMethod(
    Invocation.method(#setSearchMode, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void onSearch(String? value) => super.noSuchMethod(
    Invocation.method(#onSearch, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LocalDnsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDnsViewModel extends _i1.Mock implements _i30.LocalDnsViewModel {
  MockLocalDnsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i31.LocalDns> get localDns =>
      (super.noSuchMethod(
            Invocation.getter(#localDns),
            returnValue: <_i31.LocalDns>[],
          )
          as List<_i31.LocalDns>);

  @override
  List<_i32.DeviceOption> get deviceOptions =>
      (super.noSuchMethod(
            Invocation.getter(#deviceOptions),
            returnValue: <_i32.DeviceOption>[],
          )
          as List<_i32.DeviceOption>);

  @override
  Map<String, String> get ipToHostname =>
      (super.noSuchMethod(
            Invocation.getter(#ipToHostname),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get ipToMac =>
      (super.noSuchMethod(
            Invocation.getter(#ipToMac),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get macToIp =>
      (super.noSuchMethod(
            Invocation.getter(#macToIp),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i7.LoadStatus get loadingStatus =>
      (super.noSuchMethod(
            Invocation.getter(#loadingStatus),
            returnValue: _i7.LoadStatus.loading,
          )
          as _i7.LoadStatus);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setLoadingStatus(_i7.LoadStatus? status) => super.noSuchMethod(
    Invocation.method(#setLoadingStatus, [status]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> addLocalDns(_i31.LocalDns? item) =>
      (super.noSuchMethod(
            Invocation.method(#addLocalDns, [item]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> updateLocalDns({
    required String? oldIp,
    required _i31.LocalDns? item,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocalDns, [], {
              #oldIp: oldIp,
              #item: item,
            }),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> removeLocalDns(_i31.LocalDns? item) =>
      (super.noSuchMethod(
            Invocation.method(#removeLocalDns, [item]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  List<_i32.DeviceOption> devicesToOptions(List<_i32.Device>? devices) =>
      (super.noSuchMethod(
            Invocation.method(#devicesToOptions, [devices]),
            returnValue: <_i32.DeviceOption>[],
          )
          as List<_i32.DeviceOption>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GroupsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupsViewModel extends _i1.Mock implements _i33.GroupsViewModel {
  MockGroupsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Command<void, void> get loadGroups =>
      (super.noSuchMethod(
            Invocation.getter(#loadGroups),
            returnValue: _FakeCommand_1<void, void>(
              this,
              Invocation.getter(#loadGroups),
            ),
          )
          as _i3.Command<void, void>);

  @override
  _i3.Command<({String? comment, bool? enabled, String name}), void>
  get addGroup =>
      (super.noSuchMethod(
            Invocation.getter(#addGroup),
            returnValue:
                _FakeCommand_1<
                  ({String? comment, bool? enabled, String name}),
                  void
                >(this, Invocation.getter(#addGroup)),
          )
          as _i3.Command<
            ({String? comment, bool? enabled, String name}),
            void
          >);

  @override
  _i3.Command<({String? comment, bool? enabled, String name}), void>
  get updateGroup =>
      (super.noSuchMethod(
            Invocation.getter(#updateGroup),
            returnValue:
                _FakeCommand_1<
                  ({String? comment, bool? enabled, String name}),
                  void
                >(this, Invocation.getter(#updateGroup)),
          )
          as _i3.Command<
            ({String? comment, bool? enabled, String name}),
            void
          >);

  @override
  _i3.Command<_i34.Group, void> get deleteGroup =>
      (super.noSuchMethod(
            Invocation.getter(#deleteGroup),
            returnValue: _FakeCommand_1<_i34.Group, void>(
              this,
              Invocation.getter(#deleteGroup),
            ),
          )
          as _i3.Command<_i34.Group, void>);

  @override
  List<_i34.Group> get groups =>
      (super.noSuchMethod(
            Invocation.getter(#groups),
            returnValue: <_i34.Group>[],
          )
          as List<_i34.Group>);

  @override
  List<_i34.Group> get filteredGroups =>
      (super.noSuchMethod(
            Invocation.getter(#filteredGroups),
            returnValue: <_i34.Group>[],
          )
          as List<_i34.Group>);

  @override
  String get searchTerm =>
      (super.noSuchMethod(
            Invocation.getter(#searchTerm),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#searchTerm),
            ),
          )
          as String);

  @override
  bool get searchMode =>
      (super.noSuchMethod(Invocation.getter(#searchMode), returnValue: false)
          as bool);

  @override
  Map<int, String> get groupItems =>
      (super.noSuchMethod(
            Invocation.getter(#groupItems),
            returnValue: <int, String>{},
          )
          as Map<int, String>);

  @override
  _i7.LoadStatus get loadingStatus =>
      (super.noSuchMethod(
            Invocation.getter(#loadingStatus),
            returnValue: _i7.LoadStatus.loading,
          )
          as _i7.LoadStatus);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setSearchMode(bool? value) => super.noSuchMethod(
    Invocation.method(#setSearchMode, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void onSearch(String? value) => super.noSuchMethod(
    Invocation.method(#onSearch, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AdlistsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdlistsViewModel extends _i1.Mock implements _i35.AdlistsViewModel {
  MockAdlistsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Command<void, void> get loadAdlists =>
      (super.noSuchMethod(
            Invocation.getter(#loadAdlists),
            returnValue: _FakeCommand_1<void, void>(
              this,
              Invocation.getter(#loadAdlists),
            ),
          )
          as _i3.Command<void, void>);

  @override
  _i3.Command<_i36.Adlist, void> get deleteAdlist =>
      (super.noSuchMethod(
            Invocation.getter(#deleteAdlist),
            returnValue: _FakeCommand_1<_i36.Adlist, void>(
              this,
              Invocation.getter(#deleteAdlist),
            ),
          )
          as _i3.Command<_i36.Adlist, void>);

  @override
  _i3.Command<
    ({
      String address,
      String? comment,
      bool? enabled,
      List<int>? groups,
      _i7.ListType type,
    }),
    void
  >
  get addAdlist =>
      (super.noSuchMethod(
            Invocation.getter(#addAdlist),
            returnValue:
                _FakeCommand_1<
                  ({
                    String address,
                    String? comment,
                    bool? enabled,
                    List<int>? groups,
                    _i7.ListType type,
                  }),
                  void
                >(this, Invocation.getter(#addAdlist)),
          )
          as _i3.Command<
            ({
              String address,
              String? comment,
              bool? enabled,
              List<int>? groups,
              _i7.ListType type,
            }),
            void
          >);

  @override
  _i3.Command<_i36.Adlist, void> get updateAdlist =>
      (super.noSuchMethod(
            Invocation.getter(#updateAdlist),
            returnValue: _FakeCommand_1<_i36.Adlist, void>(
              this,
              Invocation.getter(#updateAdlist),
            ),
          )
          as _i3.Command<_i36.Adlist, void>);

  @override
  List<_i36.Adlist> get whitelistAdlists =>
      (super.noSuchMethod(
            Invocation.getter(#whitelistAdlists),
            returnValue: <_i36.Adlist>[],
          )
          as List<_i36.Adlist>);

  @override
  List<_i36.Adlist> get blacklistAdlists =>
      (super.noSuchMethod(
            Invocation.getter(#blacklistAdlists),
            returnValue: <_i36.Adlist>[],
          )
          as List<_i36.Adlist>);

  @override
  List<_i36.Adlist> get filteredWhitelistAdlists =>
      (super.noSuchMethod(
            Invocation.getter(#filteredWhitelistAdlists),
            returnValue: <_i36.Adlist>[],
          )
          as List<_i36.Adlist>);

  @override
  List<_i36.Adlist> get filteredBlacklistAdlists =>
      (super.noSuchMethod(
            Invocation.getter(#filteredBlacklistAdlists),
            returnValue: <_i36.Adlist>[],
          )
          as List<_i36.Adlist>);

  @override
  String get searchTerm =>
      (super.noSuchMethod(
            Invocation.getter(#searchTerm),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#searchTerm),
            ),
          )
          as String);

  @override
  bool get searchMode =>
      (super.noSuchMethod(Invocation.getter(#searchMode), returnValue: false)
          as bool);

  @override
  _i7.LoadStatus get loadingStatus =>
      (super.noSuchMethod(
            Invocation.getter(#loadingStatus),
            returnValue: _i7.LoadStatus.loading,
          )
          as _i7.LoadStatus);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setSelectedTab(int? tab) => super.noSuchMethod(
    Invocation.method(#setSelectedTab, [tab]),
    returnValueForMissingStub: null,
  );

  @override
  void setSearchMode(bool? value) => super.noSuchMethod(
    Invocation.method(#setSearchMode, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setGroupFilter(int? groupId) => super.noSuchMethod(
    Invocation.method(#setGroupFilter, [groupId]),
    returnValueForMissingStub: null,
  );

  @override
  void clearGroupFilter() => super.noSuchMethod(
    Invocation.method(#clearGroupFilter, []),
    returnValueForMissingStub: null,
  );

  @override
  void onSearch(String? value) => super.noSuchMethod(
    Invocation.method(#onSearch, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GravityUpdateViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockGravityUpdateViewModel extends _i1.Mock
    implements _i37.GravityUpdateViewModel {
  MockGravityUpdateViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.GravityStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i7.GravityStatus.idle,
          )
          as _i7.GravityStatus);

  @override
  List<String> get logs =>
      (super.noSuchMethod(Invocation.getter(#logs), returnValue: <String>[])
          as List<String>);

  @override
  bool get isLoaded =>
      (super.noSuchMethod(Invocation.getter(#isLoaded), returnValue: false)
          as bool);

  @override
  List<_i38.FtlMessage> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: <_i38.FtlMessage>[],
          )
          as List<_i38.FtlMessage>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void clearMessages() => super.noSuchMethod(
    Invocation.method(#clearMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearLogs() => super.noSuchMethod(
    Invocation.method(#clearLogs, []),
    returnValueForMissingStub: null,
  );

  @override
  void setStatus(_i7.GravityStatus? status) => super.noSuchMethod(
    Invocation.method(#setStatus, [status]),
    returnValueForMissingStub: null,
  );

  @override
  void setStartedAt(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setStartedAt, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void setCompletedAt(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setCompletedAt, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void appendLogs(List<String>? entries) => super.noSuchMethod(
    Invocation.method(#appendLogs, [entries]),
    returnValueForMissingStub: null,
  );

  @override
  void update({
    _i39.ActionsRepository? actionsRepository,
    _i26.FtlRepository? ftlRepository,
    String? serverAddress,
  }) => super.noSuchMethod(
    Invocation.method(#update, [], {
      #actionsRepository: actionsRepository,
      #ftlRepository: ftlRepository,
      #serverAddress: serverAddress,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<bool> removeMessage(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeMessage, [id]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
