import 'package:flutter/material.dart';
import 'package:pi_hole_client/models/query_status.dart';

final List<QueryStatus> queryStatusesV5 = [
  QueryStatus(
    index: 1,
    key: "1",
    text: "Blocked (gravity)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 2,
    key: "2",
    text: "OK (forwarded)",
    color: Colors.green,
    icon: Icons.verified_user_rounded,
  ),
  QueryStatus(
    index: 3,
    key: "3",
    text: "OK (cache)",
    color: Colors.green,
    icon: Icons.verified_user_rounded,
  ),
  QueryStatus(
    index: 4,
    key: "4",
    text: "Blocked (regex blacklist)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 5,
    key: "5",
    text: "Blocked (exact blacklist)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 6,
    key: "6",
    text: "Blocked (external, IP)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 7,
    key: "7",
    text: "Blocked (external, NULL)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 8,
    key: "8",
    text: "Blocked (external, NXRA)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 9,
    key: "9",
    text: "Blocked (gravity, CNAME)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 10,
    key: "10",
    text: "Blocked (regex blacklist, CNAME)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 11,
    key: "11",
    text: "Blocked (exact blacklist, CNAME)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 12,
    key: "12",
    text: "Retried",
    color: Colors.blue,
    icon: Icons.refresh_rounded,
  ),
  QueryStatus(
    index: 13,
    key: "13",
    text: "Retried (ignored)",
    color: Colors.blue,
    icon: Icons.refresh_rounded,
  ),
  QueryStatus(
    index: 14,
    key: "14",
    text: "OK (already forwarded)",
    color: Colors.green,
    icon: Icons.verified_user_rounded,
  ),
  QueryStatus(
    index: 14,
    key: "15",
    text: "Database is busy",
    color: Colors.orange,
    icon: Icons.storage_rounded,
    isShown: false,
  ),
];

final List<QueryStatus> queryStatusesV6 = [
  QueryStatus(
    index: 1,
    key: "UNKNOWN",
    text: "UNKNOWN",
    color: Colors.grey,
    icon: Icons.question_mark_rounded,
  ),
  QueryStatus(
    index: 2,
    key: "GRAVITY",
    text: "Blocked (gravity)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 3,
    key: "FORWARDED",
    text: "Forwarded",
    color: Colors.green,
    icon: Icons.verified_user_rounded,
  ),
  QueryStatus(
    index: 4,
    key: "CACHE",
    text: "Served from cache",
    color: Colors.green,
    icon: Icons.verified_user_rounded,
  ),
  QueryStatus(
    index: 5,
    key: "REGEX",
    text: "Blocked (regex)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 6,
    key: "DENYLIST",
    text: "Blocked (exact)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 7,
    key: "EXTERNAL_BLOCKED_IP",
    text: "Blocked (external, IP)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 8,
    key: "EXTERNAL_BLOCKED_NULL",
    text: "Blocked (external, NULL)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 9,
    key: "EXTERNAL_BLOCKED_NXRA",
    text: "Blocked (external, NXRA)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 10,
    key: "GRAVITY_CNAME",
    text: "Blocked (gravity, CNAME)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 11,
    key: "REGEX_CNAME",
    text: "Blocked (regex denied, CNAME)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 12,
    key: "DENYLIST_CNAME",
    text: "Blocked (exact denied, CNAME)",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 13,
    key: "RETRIED",
    text: "Retried",
    color: Colors.blue,
    icon: Icons.refresh_rounded,
  ),
  QueryStatus(
    index: 14,
    key: "RETRIED_DNSSEC",
    text: "Retried (ignored)",
    color: Colors.blue,
    icon: Icons.refresh_rounded,
  ),
  QueryStatus(
      index: 15,
      key: "IN_PROGRESS",
      text: "Already forwarded, awaiting reply",
      color: Colors.blue,
      icon: Icons.hourglass_bottom_rounded),
  QueryStatus(
    index: 16,
    key: "DBBUSY",
    text: "DBBUSY",
    color: Colors.orange,
    icon: Icons.storage_rounded,
  ),
  QueryStatus(
    index: 17,
    key: "SPECIAL_DOMAIN",
    text: "SPECIAL_DOMAIN",
    color: Colors.red,
    icon: Icons.gpp_bad_rounded,
  ),
  QueryStatus(
    index: 18,
    key: "CACHE_STALE",
    text: "Served by cache optimizer",
    color: Colors.blue,
    icon: Icons.cached_rounded,
  ),
  QueryStatus(
    index: 19,
    key: "EXTERNAL_BLOCKED_EDE15",
    text: "EXTERNAL_BLOCKED_EDE15",
    color: Colors.orange,
    icon: Icons.question_mark_rounded,
  ),
];
