import 'dart:convert';
import 'package:shelf/shelf.dart';
import 'package:shelf_router/shelf_router.dart';

class DomainsHandler {
  Router get router {
    final router = Router();

    router.get('/', (Request request) {
      final mockResponse = {
        "domains": [
          {
            "domain": "ad-assets.futurecdn.net",
            "unicode": "ad-assets.futurecdn.net",
            "type": "deny",
            "kind": "exact",
            "comment": "Added from Query Log",
            "groups": [0],
            "enabled": true,
            "id": 3,
            "date_added": 1727029792,
            "date_modified": 1742572135,
          },
          {
            "domain": "ck.getcookiestxt.com",
            "unicode": "ck.getcookiestxt.com",
            "type": "deny",
            "kind": "exact",
            "comment": "Added from Query Log",
            "groups": [0],
            "enabled": true,
            "id": 5,
            "date_added": 1727029858,
            "date_modified": 1730985972,
          },
          {
            "domain": "eu1.clevertap-prod.com",
            "unicode": "eu1.clevertap-prod.com",
            "type": "deny",
            "kind": "exact",
            "comment": "Added from Query Log",
            "groups": [0],
            "enabled": true,
            "id": 7,
            "date_added": 1727029866,
            "date_modified": 1730985972,
          },
          {
            "domain": "wizhumpgyros.com",
            "unicode": "wizhumpgyros.com",
            "type": "deny",
            "kind": "exact",
            "comment": "Added from Query Log",
            "groups": [0],
            "enabled": true,
            "id": 9,
            "date_added": 1727029890,
            "date_modified": 1730985972,
          },
          {
            "domain": "coccyxwickimp.com",
            "unicode": "coccyxwickimp.com",
            "type": "deny",
            "kind": "exact",
            "comment": "Added from Query Log",
            "groups": [0],
            "enabled": true,
            "id": 11,
            "date_added": 1727029895,
            "date_modified": 1730985972,
          },
          {
            "domain": "webmail-who-int.000webhostapp.com",
            "unicode": "webmail-who-int.000webhostapp.com",
            "type": "deny",
            "kind": "exact",
            "comment": "Added from Query Log",
            "groups": [0],
            "enabled": true,
            "id": 13,
            "date_added": 1727109129,
            "date_modified": 1730985972,
          },
          {
            "domain": "mdm.openapi.360.cn",
            "unicode": "mdm.openapi.360.cn",
            "type": "deny",
            "kind": "exact",
            "comment": "Added from Query Log",
            "groups": [0],
            "enabled": true,
            "id": 47,
            "date_added": 1727635984,
            "date_modified": 1731251127,
          },
          {
            "domain": "content-autofill.googleapis.com",
            "unicode": "content-autofill.googleapis.com",
            "type": "deny",
            "kind": "exact",
            "comment": "Added from Query Log",
            "groups": [0],
            "enabled": false,
            "id": 49,
            "date_added": 1727636056,
            "date_modified": 1735904008,
          },
          {
            "domain": "m.hotmail.com",
            "unicode": "m.hotmail.com",
            "type": "deny",
            "kind": "exact",
            "comment": "Added from Query Log",
            "groups": [0],
            "enabled": true,
            "id": 63,
            "date_added": 1729521763,
            "date_modified": 1730985973,
          },
          {
            "domain": "q.smart.360.cn",
            "unicode": "q.smart.360.cn",
            "type": "deny",
            "kind": "exact",
            "comment": "Added from Query Log",
            "groups": [0],
            "enabled": true,
            "id": 67,
            "date_added": 1730991674,
            "date_modified": 1731252778,
          },
          {
            "domain": "googleapis.com",
            "unicode": "googleapis.com",
            "type": "deny",
            "kind": "exact",
            "comment": null,
            "groups": [0],
            "enabled": true,
            "id": 136,
            "date_added": 1732722515,
            "date_modified": 1735904973,
          },
          {
            "domain": "firebaselogging.googleapis.com",
            "unicode": "firebaselogging.googleapis.com",
            "type": "deny",
            "kind": "exact",
            "comment": "Added from Query Log",
            "groups": [0],
            "enabled": true,
            "id": 137,
            "date_added": 1732722530,
            "date_modified": 1735904970,
          },
          {
            "domain": "firebase.googleapis.com",
            "unicode": "firebase.googleapis.com",
            "type": "deny",
            "kind": "exact",
            "comment": "Added from Query Log",
            "groups": [0],
            "enabled": true,
            "id": 139,
            "date_added": 1733821788,
            "date_modified": 1735904970,
          },
          {
            "domain": "connectivitycheck.platform.hicloud.com",
            "unicode": "connectivitycheck.platform.hicloud.com",
            "type": "deny",
            "kind": "exact",
            "comment": null,
            "groups": [0],
            "enabled": true,
            "id": 141,
            "date_added": 1738252198,
            "date_modified": 1740562643,
          },
          {
            "domain": "query.hicloud.com",
            "unicode": "query.hicloud.com",
            "type": "deny",
            "kind": "exact",
            "comment": null,
            "groups": [0],
            "enabled": true,
            "id": 142,
            "date_added": 1738252208,
            "date_modified": 1738252208,
          },
          {
            "domain": "facebook.net",
            "unicode": "facebook.net",
            "type": "deny",
            "kind": "exact",
            "comment": null,
            "groups": [0],
            "enabled": true,
            "id": 144,
            "date_added": 1742822968,
            "date_modified": 1742822968,
          },
        ],
        "took": 0.004214763641357422,
      };

      return Response.ok(
        jsonEncode(mockResponse),
        headers: {'Content-Type': 'application/json'},
      );
    });

    return router;
  }
}
