import 'dart:convert';
import 'package:shelf/shelf.dart';
import 'package:shelf_router/shelf_router.dart';

class NetworkHandler {
  Router get router {
    final router = Router();

    router.get('/gateway', (Request request) {
      final mockResponse = {
        "gateway": [
          {
            "family": "inet",
            "interface": "eth0",
            "address": "172.26.0.1",
            "local": ["172.26.0.5"],
          },
        ],
        "routes": [
          {
            "table": 254,
            "family": "inet",
            "protocol": "boot",
            "scope": "universe",
            "type": "unicast",
            "flags": [],
            "iflags": 0,
            "gateway": "172.26.0.1",
            "oif": "eth0",
            "dst": "default",
          },
          {
            "table": 254,
            "family": "inet",
            "protocol": "kernel",
            "scope": "link",
            "type": "unicast",
            "flags": [],
            "iflags": 0,
            "dst": "172.26.0.0",
            "prefsrc": "172.26.0.5",
            "oif": "eth0",
          },
          {
            "table": 255,
            "family": "inet",
            "protocol": "kernel",
            "scope": "host",
            "type": "local",
            "flags": [],
            "iflags": 0,
            "dst": "127.0.0.0",
            "prefsrc": "127.0.0.1",
            "oif": "lo",
          },
          {
            "table": 255,
            "family": "inet",
            "protocol": "kernel",
            "scope": "host",
            "type": "local",
            "flags": [],
            "iflags": 0,
            "dst": "127.0.0.1",
            "prefsrc": "127.0.0.1",
            "oif": "lo",
          },
          {
            "table": 255,
            "family": "inet",
            "protocol": "kernel",
            "scope": "link",
            "type": "broadcast",
            "flags": [],
            "iflags": 0,
            "dst": "127.255.255.255",
            "prefsrc": "127.0.0.1",
            "oif": "lo",
          },
          {
            "table": 255,
            "family": "inet",
            "protocol": "kernel",
            "scope": "host",
            "type": "local",
            "flags": [],
            "iflags": 0,
            "dst": "172.26.0.5",
            "prefsrc": "172.26.0.5",
            "oif": "eth0",
          },
          {
            "table": 255,
            "family": "inet",
            "protocol": "kernel",
            "scope": "link",
            "type": "broadcast",
            "flags": [],
            "iflags": 0,
            "dst": "172.26.255.255",
            "prefsrc": "172.26.0.5",
            "oif": "eth0",
          },
          {
            "table": 255,
            "family": "inet6",
            "protocol": "kernel",
            "scope": "universe",
            "type": "local",
            "flags": [],
            "iflags": 0,
            "dst": "::1",
            "priority": 0,
            "oif": "lo",
            "cstamp": 1748575809,
            "tstamp": 1748575809,
            "expires": 0,
            "error": 0,
            "used": 0,
            "pref": 0,
          },
        ],
        "interfaces": [
          {
            "name": "lo",
            "index": 1,
            "family": "unspec",
            "speed": null,
            "type": "loopback",
            "flags": ["up", "loopback", "running", "lower_up"],
            "ifname": "lo",
            "txqlen": 1000,
            "state": "unknown",
            "linkmode": 0,
            "mtu": 65536,
            "min_mtu": 0,
            "max_mtu": 0,
            "group": 0,
            "promiscuity": 0,
            "num_tx_queues": 1,
            "gso_max_segs": 65535,
            "gso_max_size": 65536,
            "num_rx_queues": 1,
            "carrier": true,
            "qdisc": "noqueue",
            "carrier_changes": 0,
            "carrier_up_count": 0,
            "carrier_down_count": 0,
            "proto_down": false,
            "map": 0,
            "address": "00:00:00:00:00:00",
            "broadcast": "00:00:00:00:00:00",
            "stats": {
              "rx_bytes": {"value": 631.882, "unit": "K"},
              "tx_bytes": {"value": 631.882, "unit": "K"},
              "bits": 64,
              "rx_packets": 7318,
              "tx_packets": 7318,
              "rx_errors": 0,
              "tx_errors": 0,
              "rx_dropped": 0,
              "tx_dropped": 0,
              "multicast": 0,
              "collisions": 0,
              "rx_length_errors": 0,
              "rx_over_errors": 0,
              "rx_crc_errors": 0,
              "rx_frame_errors": 0,
              "rx_fifo_errors": 0,
              "rx_missed_errors": 0,
              "tx_aborted_errors": 0,
              "tx_carrier_errors": 0,
              "tx_fifo_errors": 0,
              "tx_heartbeat_errors": 0,
              "tx_window_errors": 0,
              "rx_compressed": 0,
              "tx_compressed": 0,
              "rx_nohandler": 0,
            },
            "addresses": [
              {
                "index": 1,
                "family": "inet",
                "scope": "host",
                "flags": ["permanent"],
                "prefixlen": 8,
                "address": "127.0.0.1",
                "address_type": "loopback",
                "local": "127.0.0.1",
                "local_type": "loopback",
                "label": "lo",
                "prefered": 4294967295,
                "valid": 4294967295,
                "cstamp": 1748575822.73,
                "tstamp": 1748575822.73,
              },
              {
                "index": 1,
                "family": "inet6",
                "scope": "host",
                "flags": ["permanent"],
                "prefixlen": 128,
                "address": "::1",
                "address_type": "loopback",
                "prefered": 4294967295,
                "valid": 4294967295,
                "cstamp": 1748575822.73,
                "tstamp": 1748575822.73,
              },
            ],
          },
          {
            "name": "eth0",
            "index": 23,
            "family": "unspec",
            "speed": 10000,
            "type": "ether",
            "flags": ["up", "broadcast", "running", "multicast", "lower_up"],
            "ifname": "eth0",
            "txqlen": 0,
            "state": "up",
            "linkmode": 0,
            "mtu": 1500,
            "min_mtu": 68,
            "max_mtu": 65535,
            "group": 0,
            "promiscuity": 0,
            "num_tx_queues": 12,
            "gso_max_segs": 65535,
            "gso_max_size": 65536,
            "num_rx_queues": 12,
            "carrier": true,
            "qdisc": "noqueue",
            "carrier_changes": 2,
            "carrier_up_count": 1,
            "carrier_down_count": 1,
            "proto_down": false,
            "map": 0,
            "address": "04:43:ad:2a:00:04",
            "broadcast": "ff:ff:ff:ff:ff:ff",
            "link_kind": "veth",
            "link_netnsid": 0,
            "link": 24,
            "stats": {
              "rx_bytes": {"value": 17.927896, "unit": "M"},
              "tx_bytes": {"value": 32.886229, "unit": "M"},
              "bits": 64,
              "rx_packets": 215497,
              "tx_packets": 203769,
              "rx_errors": 0,
              "tx_errors": 0,
              "rx_dropped": 0,
              "tx_dropped": 0,
              "multicast": 0,
              "collisions": 0,
              "rx_length_errors": 0,
              "rx_over_errors": 0,
              "rx_crc_errors": 0,
              "rx_frame_errors": 0,
              "rx_fifo_errors": 0,
              "rx_missed_errors": 0,
              "tx_aborted_errors": 0,
              "tx_carrier_errors": 0,
              "tx_fifo_errors": 0,
              "tx_heartbeat_errors": 0,
              "tx_window_errors": 0,
              "rx_compressed": 0,
              "tx_compressed": 0,
              "rx_nohandler": 0,
            },
            "addresses": [
              {
                "index": 23,
                "family": "inet",
                "scope": "universe",
                "flags": ["permanent"],
                "prefixlen": 16,
                "address": "172.26.0.5",
                "address_type": "private",
                "local": "172.26.0.5",
                "local_type": "private",
                "broadcast": "172.26.255.255",
                "broadcast_type": "private",
                "label": "eth0",
                "prefered": 86400,
                "valid": 86400,
                "cstamp": 1748575822.99,
                "tstamp": 1748575822.99,
              },
            ],
          },
        ],
        "took": 0.00055408477783203125,
      };

      return Response.ok(
        jsonEncode(mockResponse),
        headers: {'Content-Type': 'application/json'},
      );
    });

    router.get('/devices', (Request request) {
      final mockResponse = {
        'devices': [
          {
            'id': 1,
            'hwaddr': '00:11:22:33:44:55',
            'interface': 'enp2s0',
            'firstSeen': 1664623620,
            'lastQuery': 1664688620,
            'numQueries': 585462,
            'macVendor': 'Digital Data Communications Asia Co.,Ltd',
            'ips': [
              {
                'ip': '192.168.1.51',
                'name': 'ubuntu-server',
                'lastSeen': 1664688620,
                'nameUpdated': 1664688620,
              },
            ],
          },
          {
            'id': 2,
            'hwaddr': '00:11:22:33:44:66',
            'interface': 'enp2s0',
            'firstSeen': 1664523620,
            'lastQuery': 1664588620,
            'numQueries': 562,
            'macVendor': null,
            'ips': [
              {
                'ip': '192.168.1.52',
                'name': 'ubuntu-server',
                'lastSeen': 1664588620,
                'nameUpdated': 1654588620,
              },
              {
                'ip': '192.168.1.62',
                'name': null,
                'lastSeen': 1664488620,
                'nameUpdated': 1654488620,
              },
            ],
          },
        ],
        'took': 0.003,
      };

      return Response.ok(
        jsonEncode(mockResponse),
        headers: {'Content-Type': 'application/json'},
      );
    });

    router.delete('/devices/<id>', (Request request, String id) {
      return Response(204);
    });

    return router;
  }
}
