import 'package:flutter/material.dart';
import 'package:pi_hole_client/config/query_status.dart';

final List<QueryStatus> queryStatusesV5 = [
  const QueryStatus(
    index: 1,
    key: '1',
    text: 'Blocked (gravity)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 2,
    key: '2',
    text: 'OK (forwarded)',
    colorCategory: QueryColorCategory.green,
    requestCategory: QueryRequestCategory.allowed,
    icon: Icons.verified_user_rounded,
  ),
  const QueryStatus(
    index: 3,
    key: '3',
    text: 'OK (cache)',
    colorCategory: QueryColorCategory.green,
    requestCategory: QueryRequestCategory.allowed,
    icon: Icons.verified_user_rounded,
  ),
  const QueryStatus(
    index: 4,
    key: '4',
    text: 'Blocked (regex blacklist)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 5,
    key: '5',
    text: 'Blocked (exact blacklist)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 6,
    key: '6',
    text: 'Blocked (external, IP)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 7,
    key: '7',
    text: 'Blocked (external, NULL)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 8,
    key: '8',
    text: 'Blocked (external, NXRA)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 9,
    key: '9',
    text: 'Blocked (gravity, CNAME)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 10,
    key: '10',
    text: 'Blocked (regex blacklist, CNAME)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 11,
    key: '11',
    text: 'Blocked (exact blacklist, CNAME)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 12,
    key: '12',
    text: 'Retried',
    colorCategory: QueryColorCategory.blue,
    requestCategory: QueryRequestCategory.retried,
    icon: Icons.refresh_rounded,
  ),
  const QueryStatus(
    index: 13,
    key: '13',
    text: 'Retried (ignored)',
    colorCategory: QueryColorCategory.blue,
    requestCategory: QueryRequestCategory.retried,
    icon: Icons.refresh_rounded,
  ),
  const QueryStatus(
    index: 14,
    key: '14',
    text: 'OK (already forwarded)',
    colorCategory: QueryColorCategory.green,
    requestCategory: QueryRequestCategory.inProgress,
    icon: Icons.verified_user_rounded,
  ),
  const QueryStatus(
    index: 15,
    key: '15',
    text: 'Database is busy',
    colorCategory: QueryColorCategory.orange,
    requestCategory: QueryRequestCategory.other,
    icon: Icons.storage_rounded,
    isShown: false,
  ),
];

final List<QueryStatus> queryStatusesV6 = [
  const QueryStatus(
    index: 1,
    key: 'UNKNOWN',
    text: 'UNKNOWN',
    colorCategory: QueryColorCategory.grey,
    requestCategory: QueryRequestCategory.other,
    icon: Icons.question_mark_rounded,
    isShown: false,
  ),
  const QueryStatus(
    index: 2,
    key: 'GRAVITY',
    text: 'Blocked (gravity)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 3,
    key: 'FORWARDED',
    text: 'Forwarded',
    colorCategory: QueryColorCategory.green,
    requestCategory: QueryRequestCategory.allowed,
    icon: Icons.verified_user_rounded,
  ),
  const QueryStatus(
    index: 4,
    key: 'CACHE',
    text: 'Served from cache',
    colorCategory: QueryColorCategory.green,
    requestCategory: QueryRequestCategory.allowed,
    icon: Icons.verified_user_rounded,
  ),
  const QueryStatus(
    index: 5,
    key: 'REGEX',
    text: 'Blocked (regex)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 6,
    key: 'DENYLIST',
    text: 'Blocked (exact)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 7,
    key: 'EXTERNAL_BLOCKED_IP',
    text: 'Blocked (external, IP)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 8,
    key: 'EXTERNAL_BLOCKED_NULL',
    text: 'Blocked (external, NULL)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 9,
    key: 'EXTERNAL_BLOCKED_NXRA',
    text: 'Blocked (external, NXRA)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 10,
    key: 'GRAVITY_CNAME',
    text: 'Blocked (gravity, CNAME)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 11,
    key: 'REGEX_CNAME',
    text: 'Blocked (regex denied, CNAME)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 12,
    key: 'DENYLIST_CNAME',
    text: 'Blocked (exact denied, CNAME)',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
  ),
  const QueryStatus(
    index: 13,
    key: 'RETRIED',
    text: 'Retried',
    colorCategory: QueryColorCategory.blue,
    requestCategory: QueryRequestCategory.retried,
    icon: Icons.refresh_rounded,
  ),
  const QueryStatus(
    index: 14,
    key: 'RETRIED_DNSSEC',
    text: 'Retried (ignored)',
    colorCategory: QueryColorCategory.blue,
    requestCategory: QueryRequestCategory.retried,
    icon: Icons.refresh_rounded,
  ),
  const QueryStatus(
    index: 15,
    key: 'IN_PROGRESS',
    text: 'Already forwarded, awaiting reply',
    colorCategory: QueryColorCategory.green,
    requestCategory: QueryRequestCategory.inProgress,
    icon: Icons.verified_user_rounded,
  ),
  const QueryStatus(
    index: 16,
    key: 'DBBUSY',
    text: 'DBBUSY',
    colorCategory: QueryColorCategory.orange,
    requestCategory: QueryRequestCategory.other,
    icon: Icons.storage_rounded,
    isShown: false,
  ),
  const QueryStatus(
    index: 17,
    key: 'SPECIAL_DOMAIN',
    text: 'SPECIAL_DOMAIN',
    colorCategory: QueryColorCategory.red,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.gpp_bad_rounded,
    isShown: false,
  ),
  const QueryStatus(
    index: 18,
    key: 'CACHE_STALE',
    text: 'Served by cache optimizer',
    colorCategory: QueryColorCategory.blue,
    requestCategory: QueryRequestCategory.allowed,
    icon: Icons.cached_rounded,
    isShown: false,
  ),
  const QueryStatus(
    index: 19,
    key: 'EXTERNAL_BLOCKED_EDE15',
    text: 'EXTERNAL_BLOCKED_EDE15',
    colorCategory: QueryColorCategory.orange,
    requestCategory: QueryRequestCategory.blocked,
    icon: Icons.question_mark_rounded,
    isShown: false,
  ),
];
