// Mocks generated by Mockito 5.4.6 from annotations
// in pi_hole_client/test/ut/providers/app_config_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:pi_hole_client/data/repositories/database_repository.dart'
    as _i4;
import 'package:pi_hole_client/domain/models/database.dart' as _i2;
import 'package:pi_hole_client/domain/models/server.dart' as _i8;
import 'package:result_dart/result_dart.dart' as _i6;
import 'package:sqflite/sqflite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppDbData_0 extends _i1.SmartFake implements _i2.AppDbData {
  _FakeAppDbData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseRepository extends _i1.Mock
    implements _i4.DatabaseRepository {
  MockDatabaseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.ServerDbData> get servers => (super.noSuchMethod(
        Invocation.getter(#servers),
        returnValue: <_i2.ServerDbData>[],
      ) as List<_i2.ServerDbData>);

  @override
  _i2.AppDbData get appConfig => (super.noSuchMethod(
        Invocation.getter(#appConfig),
        returnValue: _FakeAppDbData_0(
          this,
          Invocation.getter(#appConfig),
        ),
      ) as _i2.AppDbData);

  @override
  _i3.Database get dbInstance => (super.noSuchMethod(
        Invocation.getter(#dbInstance),
        returnValue: _FakeDatabase_1(
          this,
          Invocation.getter(#dbInstance),
        ),
      ) as _i3.Database);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> initialize() =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<bool> closeDb() => (super.noSuchMethod(
        Invocation.method(
          #closeDb,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> saveServerQuery(
          _i8.Server? server) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveServerQuery,
          [server],
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveServerQuery,
            [server],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> editServerQuery(
          _i8.Server? server) =>
      (super.noSuchMethod(
        Invocation.method(
          #editServerQuery,
          [server],
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #editServerQuery,
            [server],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> setDefaultServerQuery(
          String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDefaultServerQuery,
          [url],
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #setDefaultServerQuery,
            [url],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> removeServerQuery(
    String? address, {
    _i3.Transaction? txn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeServerQuery,
          [address],
          {#txn: txn},
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #removeServerQuery,
            [address],
            {#txn: txn},
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> deleteServersDataQuery(
          {_i3.Transaction? txn}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteServersDataQuery,
          [],
          {#txn: txn},
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #deleteServersDataQuery,
            [],
            {#txn: txn},
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<bool, Exception>> checkUrlExistsQuery(
          String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkUrlExistsQuery,
          [url],
        ),
        returnValue: _i5.Future<_i6.ResultDart<bool, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<bool, Exception>>(
          this,
          Invocation.method(
            #checkUrlExistsQuery,
            [url],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<bool, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> updateConfigQuery({
    required String? column,
    required Object? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConfigQuery,
          [],
          {
            #column: column,
            #value: value,
          },
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #updateConfigQuery,
            [],
            {
              #column: column,
              #value: value,
            },
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> restoreAppConfigQuery() =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreAppConfigQuery,
          [],
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #restoreAppConfigQuery,
            [],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> cleanUpSecureStorage() =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanUpSecureStorage,
          [],
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #cleanUpSecureStorage,
            [],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<
      _i6.ResultDart<_i2.GravityUpdateData, Exception>> getGravityUpdateQuery(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGravityUpdateQuery,
          [address],
        ),
        returnValue: _i5
            .Future<_i6.ResultDart<_i2.GravityUpdateData, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<_i2.GravityUpdateData, Exception>>(
          this,
          Invocation.method(
            #getGravityUpdateQuery,
            [address],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<_i2.GravityUpdateData, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> upsertGravityUpdateQuery(
          _i2.GravityUpdateData? gravityUpdateData) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertGravityUpdateQuery,
          [gravityUpdateData],
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #upsertGravityUpdateQuery,
            [gravityUpdateData],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> removeGravityUpdateQuery(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeGravityUpdateQuery,
          [address],
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #removeGravityUpdateQuery,
            [address],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<
      _i6.ResultDart<List<_i2.GravityLogsData>, Exception>> getGravityLogsQuery(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGravityLogsQuery,
          [address],
        ),
        returnValue: _i5
            .Future<_i6.ResultDart<List<_i2.GravityLogsData>, Exception>>.value(
            _i7.dummyValue<
                _i6.ResultDart<List<_i2.GravityLogsData>, Exception>>(
          this,
          Invocation.method(
            #getGravityLogsQuery,
            [address],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<List<_i2.GravityLogsData>, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> insertGravityLogQuery(
          List<_i2.GravityLogsData>? gravityLogsDataList) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertGravityLogQuery,
          [gravityLogsDataList],
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #insertGravityLogQuery,
            [gravityLogsDataList],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> clearGravityLogsQuery(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearGravityLogsQuery,
          [address],
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #clearGravityLogsQuery,
            [address],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<List<_i2.GravityMessagesData>, Exception>>
      getGravityMessagesQuery(String? address) => (super.noSuchMethod(
            Invocation.method(
              #getGravityMessagesQuery,
              [address],
            ),
            returnValue: _i5.Future<
                _i6.ResultDart<List<_i2.GravityMessagesData>,
                    Exception>>.value(_i7.dummyValue<
                _i6.ResultDart<List<_i2.GravityMessagesData>, Exception>>(
              this,
              Invocation.method(
                #getGravityMessagesQuery,
                [address],
              ),
            )),
          ) as _i5.Future<
              _i6.ResultDart<List<_i2.GravityMessagesData>, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> insertGravityMessageQuery(
          List<_i2.GravityMessagesData>? messagesList) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertGravityMessageQuery,
          [messagesList],
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #insertGravityMessageQuery,
            [messagesList],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> clearGravityMessagesQuery(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearGravityMessagesQuery,
          [address],
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #clearGravityMessagesQuery,
            [address],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<_i2.GravityData, Exception>> getGravityDataQuery(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGravityDataQuery,
          [address],
        ),
        returnValue:
            _i5.Future<_i6.ResultDart<_i2.GravityData, Exception>>.value(
                _i7.dummyValue<_i6.ResultDart<_i2.GravityData, Exception>>(
          this,
          Invocation.method(
            #getGravityDataQuery,
            [address],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<_i2.GravityData, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> clearGravityDataQuery(
    String? address, {
    _i3.Transaction? txn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearGravityDataQuery,
          [address],
          {#txn: txn},
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #clearGravityDataQuery,
            [address],
            {#txn: txn},
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> clearAllGravityDataQuery(
          {_i3.Transaction? txn}) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearAllGravityDataQuery,
          [],
          {#txn: txn},
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #clearAllGravityDataQuery,
            [],
            {#txn: txn},
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);

  @override
  _i5.Future<_i6.ResultDart<void, Exception>> deleteMessageQuery(
    String? address,
    int? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessageQuery,
          [
            address,
            id,
          ],
        ),
        returnValue: _i5.Future<_i6.ResultDart<void, Exception>>.value(
            _i7.dummyValue<_i6.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #deleteMessageQuery,
            [
              address,
              id,
            ],
          ),
        )),
      ) as _i5.Future<_i6.ResultDart<void, Exception>>);
}
