// Mocks generated by Mockito 5.4.6 from annotations
// in pi_hole_client/test/ut/providers/filters_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pi_hole_client/data/gateway/api_gateway_interface.dart' as _i7;
import 'package:pi_hole_client/domain/models_old/database.dart' as _i9;
import 'package:pi_hole_client/domain/models_old/query_status.dart' as _i5;
import 'package:pi_hole_client/domain/models_old/server.dart' as _i4;
import 'package:pi_hole_client/ui/core/themes/theme.dart' as _i2;
import 'package:pi_hole_client/ui/core/viewmodel/app_config_provider.dart'
    as _i6;
import 'package:pi_hole_client/ui/core/viewmodel/servers_provider.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppColors_0 extends _i1.SmartFake implements _i2.AppColors {
  _FakeAppColors_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServersProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockServersProvider extends _i1.Mock implements _i3.ServersProvider {
  MockServersProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppColors get colors =>
      (super.noSuchMethod(
            Invocation.getter(#colors),
            returnValue: _FakeAppColors_0(this, Invocation.getter(#colors)),
          )
          as _i2.AppColors);

  @override
  List<_i4.Server> get getServersList =>
      (super.noSuchMethod(
            Invocation.getter(#getServersList),
            returnValue: <_i4.Server>[],
          )
          as List<_i4.Server>);

  @override
  List<_i4.Server> get serversWithUnverifiedCertificates =>
      (super.noSuchMethod(
            Invocation.getter(#serversWithUnverifiedCertificates),
            returnValue: <_i4.Server>[],
          )
          as List<_i4.Server>);

  @override
  int get numShown =>
      (super.noSuchMethod(Invocation.getter(#numShown), returnValue: 0) as int);

  @override
  List<_i5.QueryStatus> get queryStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#queryStatuses),
            returnValue: <_i5.QueryStatus>[],
          )
          as List<_i5.QueryStatus>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void update(_i6.AppConfigProvider? provider) => super.noSuchMethod(
    Invocation.method(#update, [provider]),
    returnValueForMissingStub: null,
  );

  @override
  void setConnectingServer(_i4.Server? server) => super.noSuchMethod(
    Invocation.method(#setConnectingServer, [server]),
    returnValueForMissingStub: null,
  );

  @override
  void clearConnectingServer() => super.noSuchMethod(
    Invocation.method(#clearConnectingServer, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.ApiGateway? loadApiGateway(_i4.Server? server) =>
      (super.noSuchMethod(Invocation.method(#loadApiGateway, [server]))
          as _i7.ApiGateway?);

  @override
  _i7.ApiGateway? createApiGateway(_i4.Server? server) =>
      (super.noSuchMethod(Invocation.method(#createApiGateway, [server]))
          as _i7.ApiGateway?);

  @override
  _i5.QueryStatus? getQueryStatus(String? key) =>
      (super.noSuchMethod(Invocation.method(#getQueryStatus, [key]))
          as _i5.QueryStatus?);

  @override
  _i5.QueryStatus? findQueryStatus(String? key) =>
      (super.noSuchMethod(Invocation.method(#findQueryStatus, [key]))
          as _i5.QueryStatus?);

  @override
  _i8.Future<bool> addServer(_i4.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#addServer, [server]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> editServer(_i4.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#editServer, [server]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> removeServer(String? serverAddress) =>
      (super.noSuchMethod(
            Invocation.method(#removeServer, [serverAddress]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> setDefaultServer(_i4.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultServer, [server]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<dynamic> saveFromDb(List<_i9.ServerDbData>? servers) =>
      (super.noSuchMethod(
            Invocation.method(#saveFromDb, [servers]),
            returnValue: _i8.Future<dynamic>.value(),
          )
          as _i8.Future<dynamic>);

  @override
  _i8.FutureOr<Map<String, dynamic>> checkUrlExists(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#checkUrlExists, [url]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.FutureOr<Map<String, dynamic>>);

  @override
  void setselectedServer({required _i4.Server? server, bool? toHomeTab}) =>
      super.noSuchMethod(
        Invocation.method(#setselectedServer, [], {
          #server: server,
          #toHomeTab: toHomeTab,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void updateselectedServerStatus(bool? enabled) => super.noSuchMethod(
    Invocation.method(#updateselectedServerStatus, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> deleteDbData() =>
      (super.noSuchMethod(
            Invocation.method(#deleteDbData, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> resetSelectedServer() =>
      (super.noSuchMethod(
            Invocation.method(#resetSelectedServer, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
