// Mocks generated by Mockito 5.4.5 from annotations
// in pi_hole_client/test/ut/providers/gravity_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:pi_hole_client/config/theme.dart' as _i2;
import 'package:pi_hole_client/gateways/api_gateway_interface.dart' as _i11;
import 'package:pi_hole_client/gateways/v6/api_gateway_v6.dart' as _i15;
import 'package:pi_hole_client/models/domain.dart' as _i17;
import 'package:pi_hole_client/models/gateways.dart' as _i7;
import 'package:pi_hole_client/models/groups.dart' as _i19;
import 'package:pi_hole_client/models/query_status.dart' as _i9;
import 'package:pi_hole_client/models/repository/database.dart' as _i3;
import 'package:pi_hole_client/models/server.dart' as _i5;
import 'package:pi_hole_client/models/subscriptions.dart' as _i18;
import 'package:pi_hole_client/providers/app_config_provider.dart' as _i10;
import 'package:pi_hole_client/providers/servers_provider.dart' as _i8;
import 'package:pi_hole_client/repository/database.dart' as _i14;
import 'package:sqflite/sqflite.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppColors_0 extends _i1.SmartFake implements _i2.AppColors {
  _FakeAppColors_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppDbData_1 extends _i1.SmartFake implements _i3.AppDbData {
  _FakeAppDbData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_2 extends _i1.SmartFake implements _i4.Database {
  _FakeDatabase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePiHoleClientData_3 extends _i1.SmartFake
    implements _i3.PiHoleClientData {
  _FakePiHoleClientData_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeServer_4 extends _i1.SmartFake implements _i5.Server {
  _FakeServer_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_5 extends _i1.SmartFake implements _i6.Response {
  _FakeResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_6 extends _i1.SmartFake
    implements _i6.StreamedResponse {
  _FakeStreamedResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginQueryResponse_7 extends _i1.SmartFake
    implements _i7.LoginQueryResponse {
  _FakeLoginQueryResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeStatusResponse_8 extends _i1.SmartFake
    implements _i7.RealtimeStatusResponse {
  _FakeRealtimeStatusResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDisableServerResponse_9 extends _i1.SmartFake
    implements _i7.DisableServerResponse {
  _FakeDisableServerResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEnableServerResponse_10 extends _i1.SmartFake
    implements _i7.EnableServerResponse {
  _FakeEnableServerResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFetchOverTimeDataResponse_11 extends _i1.SmartFake
    implements _i7.FetchOverTimeDataResponse {
  _FakeFetchOverTimeDataResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFetchLogsResponse_12 extends _i1.SmartFake
    implements _i7.FetchLogsResponse {
  _FakeFetchLogsResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSetWhiteBlacklistResponse_13 extends _i1.SmartFake
    implements _i7.SetWhiteBlacklistResponse {
  _FakeSetWhiteBlacklistResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetDomainLists_14 extends _i1.SmartFake
    implements _i7.GetDomainLists {
  _FakeGetDomainLists_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveDomainFromListResponse_15 extends _i1.SmartFake
    implements _i7.RemoveDomainFromListResponse {
  _FakeRemoveDomainFromListResponse_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeAddDomainToListResponse_16 extends _i1.SmartFake
    implements _i7.AddDomainToListResponse {
  _FakeAddDomainToListResponse_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHostResponse_17 extends _i1.SmartFake implements _i7.HostResponse {
  _FakeHostResponse_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSensorsResponse_18 extends _i1.SmartFake
    implements _i7.SensorsResponse {
  _FakeSensorsResponse_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSystemResponse_19 extends _i1.SmartFake
    implements _i7.SystemResponse {
  _FakeSystemResponse_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVersionResponse_20 extends _i1.SmartFake
    implements _i7.VersionResponse {
  _FakeVersionResponse_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePiHoleServerInfoResponse_21 extends _i1.SmartFake
    implements _i7.PiHoleServerInfoResponse {
  _FakePiHoleServerInfoResponse_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubscriptionsResponse_22 extends _i1.SmartFake
    implements _i7.SubscriptionsResponse {
  _FakeSubscriptionsResponse_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveSubscriptionResponse_23 extends _i1.SmartFake
    implements _i7.RemoveSubscriptionResponse {
  _FakeRemoveSubscriptionResponse_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchResponse_24 extends _i1.SmartFake
    implements _i7.SearchResponse {
  _FakeSearchResponse_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGroupsResponse_25 extends _i1.SmartFake
    implements _i7.GroupsResponse {
  _FakeGroupsResponse_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveGroupResponse_26 extends _i1.SmartFake
    implements _i7.RemoveGroupResponse {
  _FakeRemoveGroupResponse_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessagesResponse_27 extends _i1.SmartFake
    implements _i7.MessagesResponse {
  _FakeMessagesResponse_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveMessagesResponse_28 extends _i1.SmartFake
    implements _i7.RemoveMessagesResponse {
  _FakeRemoveMessagesResponse_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServersProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockServersProvider extends _i1.Mock implements _i8.ServersProvider {
  MockServersProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppColors get colors =>
      (super.noSuchMethod(
            Invocation.getter(#colors),
            returnValue: _FakeAppColors_0(this, Invocation.getter(#colors)),
          )
          as _i2.AppColors);

  @override
  List<_i5.Server> get getServersList =>
      (super.noSuchMethod(
            Invocation.getter(#getServersList),
            returnValue: <_i5.Server>[],
          )
          as List<_i5.Server>);

  @override
  int get numShown =>
      (super.noSuchMethod(Invocation.getter(#numShown), returnValue: 0) as int);

  @override
  List<_i9.QueryStatus> get queryStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#queryStatuses),
            returnValue: <_i9.QueryStatus>[],
          )
          as List<_i9.QueryStatus>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void update(_i10.AppConfigProvider? provider) => super.noSuchMethod(
    Invocation.method(#update, [provider]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.ApiGateway? loadApiGateway(_i5.Server? server) =>
      (super.noSuchMethod(Invocation.method(#loadApiGateway, [server]))
          as _i11.ApiGateway?);

  @override
  _i9.QueryStatus? getQueryStatus(String? key) =>
      (super.noSuchMethod(Invocation.method(#getQueryStatus, [key]))
          as _i9.QueryStatus?);

  @override
  _i9.QueryStatus? findQueryStatus(String? key) =>
      (super.noSuchMethod(Invocation.method(#findQueryStatus, [key]))
          as _i9.QueryStatus?);

  @override
  _i12.Future<bool> addServer(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#addServer, [server]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> editServer(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#editServer, [server]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> removeServer(String? serverAddress) =>
      (super.noSuchMethod(
            Invocation.method(#removeServer, [serverAddress]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> setDefaultServer(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultServer, [server]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<dynamic> saveFromDb(List<_i3.ServerDbData>? servers) =>
      (super.noSuchMethod(
            Invocation.method(#saveFromDb, [servers]),
            returnValue: _i12.Future<dynamic>.value(),
          )
          as _i12.Future<dynamic>);

  @override
  _i12.FutureOr<Map<String, dynamic>> checkUrlExists(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#checkUrlExists, [url]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.FutureOr<Map<String, dynamic>>);

  @override
  void setselectedServer({required _i5.Server? server, bool? toHomeTab}) =>
      super.noSuchMethod(
        Invocation.method(#setselectedServer, [], {
          #server: server,
          #toHomeTab: toHomeTab,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void updateselectedServerStatus(bool? enabled) => super.noSuchMethod(
    Invocation.method(#updateselectedServerStatus, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<bool> deleteDbData() =>
      (super.noSuchMethod(
            Invocation.method(#deleteDbData, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> resetSelectedServer() =>
      (super.noSuchMethod(
            Invocation.method(#resetSelectedServer, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DatabaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseRepository extends _i1.Mock
    implements _i14.DatabaseRepository {
  MockDatabaseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.ServerDbData> get servers =>
      (super.noSuchMethod(
            Invocation.getter(#servers),
            returnValue: <_i3.ServerDbData>[],
          )
          as List<_i3.ServerDbData>);

  @override
  _i3.AppDbData get appConfig =>
      (super.noSuchMethod(
            Invocation.getter(#appConfig),
            returnValue: _FakeAppDbData_1(this, Invocation.getter(#appConfig)),
          )
          as _i3.AppDbData);

  @override
  _i4.Database get dbInstance =>
      (super.noSuchMethod(
            Invocation.getter(#dbInstance),
            returnValue: _FakeDatabase_2(this, Invocation.getter(#dbInstance)),
          )
          as _i4.Database);

  @override
  _i12.Future<void> initialize({String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {#path: path}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  Map<String, dynamic> toDict() =>
      (super.noSuchMethod(
            Invocation.method(#toDict, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<_i3.PiHoleClientData> loadDb({String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#loadDb, [], {#path: path}),
            returnValue: _i12.Future<_i3.PiHoleClientData>.value(
              _FakePiHoleClientData_3(
                this,
                Invocation.method(#loadDb, [], {#path: path}),
              ),
            ),
          )
          as _i12.Future<_i3.PiHoleClientData>);

  @override
  _i12.Future<bool> closeDb() =>
      (super.noSuchMethod(
            Invocation.method(#closeDb, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool?> saveServerQuery(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#saveServerQuery, [server]),
            returnValue: _i12.Future<bool?>.value(),
          )
          as _i12.Future<bool?>);

  @override
  _i12.Future<bool> editServerQuery(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#editServerQuery, [server]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool?> setDefaultServerQuery(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultServerQuery, [url]),
            returnValue: _i12.Future<bool?>.value(),
          )
          as _i12.Future<bool?>);

  @override
  _i12.Future<bool> removeServerQuery(
    String? address, {
    _i4.Transaction? txn,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeServerQuery, [address], {#txn: txn}),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> deleteServersDataQuery({_i4.Transaction? txn}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteServersDataQuery, [], {#txn: txn}),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<Map<String, dynamic>> checkUrlExistsQuery(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#checkUrlExistsQuery, [url]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<bool> updateConfigQuery({
    required String? column,
    required Object? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateConfigQuery, [], {
              #column: column,
              #value: value,
            }),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> restoreAppConfigQuery() =>
      (super.noSuchMethod(
            Invocation.method(#restoreAppConfigQuery, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> cleanUpSecureStorage() =>
      (super.noSuchMethod(
            Invocation.method(#cleanUpSecureStorage, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i3.GravityUpdateData?> getGravityUpdateQuery(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#getGravityUpdateQuery, [address]),
            returnValue: _i12.Future<_i3.GravityUpdateData?>.value(),
          )
          as _i12.Future<_i3.GravityUpdateData?>);

  @override
  _i12.Future<bool> upsertGravityUpdateQuery(
    _i3.GravityUpdateData? gravityUpdateData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertGravityUpdateQuery, [gravityUpdateData]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> removeGravityUpdateQuery(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#removeGravityUpdateQuery, [address]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<List<_i3.GravityLogsData>?> getGravityLogsQuery(
    String? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGravityLogsQuery, [address]),
            returnValue: _i12.Future<List<_i3.GravityLogsData>?>.value(),
          )
          as _i12.Future<List<_i3.GravityLogsData>?>);

  @override
  _i12.Future<bool> insertGravityLogQuery(
    List<_i3.GravityLogsData>? gravityLogsDataList,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertGravityLogQuery, [gravityLogsDataList]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> clearGravityLogsQuery(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#clearGravityLogsQuery, [address]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<List<_i3.GravityMessagesData>?> getGravityMessagesQuery(
    String? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGravityMessagesQuery, [address]),
            returnValue: _i12.Future<List<_i3.GravityMessagesData>?>.value(),
          )
          as _i12.Future<List<_i3.GravityMessagesData>?>);

  @override
  _i12.Future<bool> insertGravityMessageQuery(
    List<_i3.GravityMessagesData>? messagesList,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertGravityMessageQuery, [messagesList]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> clearGravityMessagesQuery(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#clearGravityMessagesQuery, [address]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<_i3.GravityData?> getGravityDataQuery(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#getGravityDataQuery, [address]),
            returnValue: _i12.Future<_i3.GravityData?>.value(),
          )
          as _i12.Future<_i3.GravityData?>);

  @override
  _i12.Future<bool> clearGravityDataQuery(
    String? address, {
    _i4.Transaction? txn,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clearGravityDataQuery, [address], {#txn: txn}),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> clearAllGravityDataQuery({_i4.Transaction? txn}) =>
      (super.noSuchMethod(
            Invocation.method(#clearAllGravityDataQuery, [], {#txn: txn}),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);
}

/// A class which mocks [ApiGatewayV6].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiGatewayV6 extends _i1.Mock implements _i15.ApiGatewayV6 {
  MockApiGatewayV6() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get unexpectedError =>
      (super.noSuchMethod(
            Invocation.getter(#unexpectedError),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#unexpectedError),
            ),
          )
          as String);

  @override
  String get fetchError =>
      (super.noSuchMethod(
            Invocation.getter(#fetchError),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#fetchError),
            ),
          )
          as String);

  @override
  _i5.Server get server =>
      (super.noSuchMethod(
            Invocation.getter(#server),
            returnValue: _FakeServer_4(this, Invocation.getter(#server)),
          )
          as _i5.Server);

  @override
  _i12.Future<_i6.Response> httpClient({
    required String? method,
    required String? url,
    Map<String, String>? headers,
    Map<String, dynamic>? body,
    int? timeout = 10,
    int? maxRetries = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#httpClient, [], {
              #method: method,
              #url: url,
              #headers: headers,
              #body: body,
              #timeout: timeout,
              #maxRetries: maxRetries,
            }),
            returnValue: _i12.Future<_i6.Response>.value(
              _FakeResponse_5(
                this,
                Invocation.method(#httpClient, [], {
                  #method: method,
                  #url: url,
                  #headers: headers,
                  #body: body,
                  #timeout: timeout,
                  #maxRetries: maxRetries,
                }),
              ),
            ),
          )
          as _i12.Future<_i6.Response>);

  @override
  _i12.Future<_i6.StreamedResponse> httpClientStream({
    required String? method,
    required String? url,
    Map<String, String>? headers,
    Map<String, dynamic>? body,
    int? timeout = 10,
    int? maxRetries = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#httpClientStream, [], {
              #method: method,
              #url: url,
              #headers: headers,
              #body: body,
              #timeout: timeout,
              #maxRetries: maxRetries,
            }),
            returnValue: _i12.Future<_i6.StreamedResponse>.value(
              _FakeStreamedResponse_6(
                this,
                Invocation.method(#httpClientStream, [], {
                  #method: method,
                  #url: url,
                  #headers: headers,
                  #body: body,
                  #timeout: timeout,
                  #maxRetries: maxRetries,
                }),
              ),
            ),
          )
          as _i12.Future<_i6.StreamedResponse>);

  @override
  _i12.Future<_i7.LoginQueryResponse> loginQuery({bool? refresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#loginQuery, [], {#refresh: refresh}),
            returnValue: _i12.Future<_i7.LoginQueryResponse>.value(
              _FakeLoginQueryResponse_7(
                this,
                Invocation.method(#loginQuery, [], {#refresh: refresh}),
              ),
            ),
          )
          as _i12.Future<_i7.LoginQueryResponse>);

  @override
  _i12.Future<_i7.RealtimeStatusResponse> realtimeStatus() =>
      (super.noSuchMethod(
            Invocation.method(#realtimeStatus, []),
            returnValue: _i12.Future<_i7.RealtimeStatusResponse>.value(
              _FakeRealtimeStatusResponse_8(
                this,
                Invocation.method(#realtimeStatus, []),
              ),
            ),
          )
          as _i12.Future<_i7.RealtimeStatusResponse>);

  @override
  _i12.Future<_i7.DisableServerResponse> disableServerRequest(int? time) =>
      (super.noSuchMethod(
            Invocation.method(#disableServerRequest, [time]),
            returnValue: _i12.Future<_i7.DisableServerResponse>.value(
              _FakeDisableServerResponse_9(
                this,
                Invocation.method(#disableServerRequest, [time]),
              ),
            ),
          )
          as _i12.Future<_i7.DisableServerResponse>);

  @override
  _i12.Future<_i7.EnableServerResponse> enableServerRequest() =>
      (super.noSuchMethod(
            Invocation.method(#enableServerRequest, []),
            returnValue: _i12.Future<_i7.EnableServerResponse>.value(
              _FakeEnableServerResponse_10(
                this,
                Invocation.method(#enableServerRequest, []),
              ),
            ),
          )
          as _i12.Future<_i7.EnableServerResponse>);

  @override
  _i12.Future<_i7.FetchOverTimeDataResponse> fetchOverTimeData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchOverTimeData, []),
            returnValue: _i12.Future<_i7.FetchOverTimeDataResponse>.value(
              _FakeFetchOverTimeDataResponse_11(
                this,
                Invocation.method(#fetchOverTimeData, []),
              ),
            ),
          )
          as _i12.Future<_i7.FetchOverTimeDataResponse>);

  @override
  _i12.Future<_i7.FetchLogsResponse> fetchLogs(
    DateTime? from,
    DateTime? until,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLogs, [from, until]),
            returnValue: _i12.Future<_i7.FetchLogsResponse>.value(
              _FakeFetchLogsResponse_12(
                this,
                Invocation.method(#fetchLogs, [from, until]),
              ),
            ),
          )
          as _i12.Future<_i7.FetchLogsResponse>);

  @override
  _i12.Future<_i7.SetWhiteBlacklistResponse> setWhiteBlacklist(
    String? domain,
    String? list,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setWhiteBlacklist, [domain, list]),
            returnValue: _i12.Future<_i7.SetWhiteBlacklistResponse>.value(
              _FakeSetWhiteBlacklistResponse_13(
                this,
                Invocation.method(#setWhiteBlacklist, [domain, list]),
              ),
            ),
          )
          as _i12.Future<_i7.SetWhiteBlacklistResponse>);

  @override
  _i12.Future<_i7.GetDomainLists> getDomainLists() =>
      (super.noSuchMethod(
            Invocation.method(#getDomainLists, []),
            returnValue: _i12.Future<_i7.GetDomainLists>.value(
              _FakeGetDomainLists_14(
                this,
                Invocation.method(#getDomainLists, []),
              ),
            ),
          )
          as _i12.Future<_i7.GetDomainLists>);

  @override
  _i12.Future<_i7.RemoveDomainFromListResponse> removeDomainFromList(
    _i17.Domain? domain,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeDomainFromList, [domain]),
            returnValue: _i12.Future<_i7.RemoveDomainFromListResponse>.value(
              _FakeRemoveDomainFromListResponse_15(
                this,
                Invocation.method(#removeDomainFromList, [domain]),
              ),
            ),
          )
          as _i12.Future<_i7.RemoveDomainFromListResponse>);

  @override
  _i12.Future<_i7.AddDomainToListResponse> addDomainToList(
    Map<String, dynamic>? domainData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addDomainToList, [domainData]),
            returnValue: _i12.Future<_i7.AddDomainToListResponse>.value(
              _FakeAddDomainToListResponse_16(
                this,
                Invocation.method(#addDomainToList, [domainData]),
              ),
            ),
          )
          as _i12.Future<_i7.AddDomainToListResponse>);

  @override
  _i12.Future<_i7.HostResponse> fetchHostInfo() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHostInfo, []),
            returnValue: _i12.Future<_i7.HostResponse>.value(
              _FakeHostResponse_17(this, Invocation.method(#fetchHostInfo, [])),
            ),
          )
          as _i12.Future<_i7.HostResponse>);

  @override
  _i12.Future<_i7.SensorsResponse> fetchSensorsInfo() =>
      (super.noSuchMethod(
            Invocation.method(#fetchSensorsInfo, []),
            returnValue: _i12.Future<_i7.SensorsResponse>.value(
              _FakeSensorsResponse_18(
                this,
                Invocation.method(#fetchSensorsInfo, []),
              ),
            ),
          )
          as _i12.Future<_i7.SensorsResponse>);

  @override
  _i12.Future<_i7.SystemResponse> fetchSystemInfo() =>
      (super.noSuchMethod(
            Invocation.method(#fetchSystemInfo, []),
            returnValue: _i12.Future<_i7.SystemResponse>.value(
              _FakeSystemResponse_19(
                this,
                Invocation.method(#fetchSystemInfo, []),
              ),
            ),
          )
          as _i12.Future<_i7.SystemResponse>);

  @override
  _i12.Future<_i7.VersionResponse> fetchVersionInfo() =>
      (super.noSuchMethod(
            Invocation.method(#fetchVersionInfo, []),
            returnValue: _i12.Future<_i7.VersionResponse>.value(
              _FakeVersionResponse_20(
                this,
                Invocation.method(#fetchVersionInfo, []),
              ),
            ),
          )
          as _i12.Future<_i7.VersionResponse>);

  @override
  _i12.Future<_i7.PiHoleServerInfoResponse> fetchAllServerInfo() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllServerInfo, []),
            returnValue: _i12.Future<_i7.PiHoleServerInfoResponse>.value(
              _FakePiHoleServerInfoResponse_21(
                this,
                Invocation.method(#fetchAllServerInfo, []),
              ),
            ),
          )
          as _i12.Future<_i7.PiHoleServerInfoResponse>);

  @override
  _i12.Future<_i7.SubscriptionsResponse> getSubscriptions({
    String? url,
    String? stype,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptions, [], {
              #url: url,
              #stype: stype,
            }),
            returnValue: _i12.Future<_i7.SubscriptionsResponse>.value(
              _FakeSubscriptionsResponse_22(
                this,
                Invocation.method(#getSubscriptions, [], {
                  #url: url,
                  #stype: stype,
                }),
              ),
            ),
          )
          as _i12.Future<_i7.SubscriptionsResponse>);

  @override
  _i12.Future<_i7.RemoveSubscriptionResponse> removeSubscription({
    required String? url,
    String? stype,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeSubscription, [], {
              #url: url,
              #stype: stype,
            }),
            returnValue: _i12.Future<_i7.RemoveSubscriptionResponse>.value(
              _FakeRemoveSubscriptionResponse_23(
                this,
                Invocation.method(#removeSubscription, [], {
                  #url: url,
                  #stype: stype,
                }),
              ),
            ),
          )
          as _i12.Future<_i7.RemoveSubscriptionResponse>);

  @override
  _i12.Future<_i7.SubscriptionsResponse> createSubscription({
    required _i18.SubscriptionRequest? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSubscription, [], {#body: body}),
            returnValue: _i12.Future<_i7.SubscriptionsResponse>.value(
              _FakeSubscriptionsResponse_22(
                this,
                Invocation.method(#createSubscription, [], {#body: body}),
              ),
            ),
          )
          as _i12.Future<_i7.SubscriptionsResponse>);

  @override
  _i12.Future<_i7.SubscriptionsResponse> updateSubscription({
    required _i18.SubscriptionRequest? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubscription, [], {#body: body}),
            returnValue: _i12.Future<_i7.SubscriptionsResponse>.value(
              _FakeSubscriptionsResponse_22(
                this,
                Invocation.method(#updateSubscription, [], {#body: body}),
              ),
            ),
          )
          as _i12.Future<_i7.SubscriptionsResponse>);

  @override
  _i12.Future<_i7.SearchResponse> searchSubscriptions({
    required String? domain,
    bool? partial,
    int? limit,
    bool? debug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchSubscriptions, [], {
              #domain: domain,
              #partial: partial,
              #limit: limit,
              #debug: debug,
            }),
            returnValue: _i12.Future<_i7.SearchResponse>.value(
              _FakeSearchResponse_24(
                this,
                Invocation.method(#searchSubscriptions, [], {
                  #domain: domain,
                  #partial: partial,
                  #limit: limit,
                  #debug: debug,
                }),
              ),
            ),
          )
          as _i12.Future<_i7.SearchResponse>);

  @override
  _i12.Future<_i7.GroupsResponse> getGroups({String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#getGroups, [], {#name: name}),
            returnValue: _i12.Future<_i7.GroupsResponse>.value(
              _FakeGroupsResponse_25(
                this,
                Invocation.method(#getGroups, [], {#name: name}),
              ),
            ),
          )
          as _i12.Future<_i7.GroupsResponse>);

  @override
  _i12.Future<_i7.RemoveGroupResponse> removeGroup({required String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#removeGroup, [], {#name: name}),
            returnValue: _i12.Future<_i7.RemoveGroupResponse>.value(
              _FakeRemoveGroupResponse_26(
                this,
                Invocation.method(#removeGroup, [], {#name: name}),
              ),
            ),
          )
          as _i12.Future<_i7.RemoveGroupResponse>);

  @override
  _i12.Future<_i7.GroupsResponse> createGroup({
    required _i19.GroupRequest? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGroup, [], {#body: body}),
            returnValue: _i12.Future<_i7.GroupsResponse>.value(
              _FakeGroupsResponse_25(
                this,
                Invocation.method(#createGroup, [], {#body: body}),
              ),
            ),
          )
          as _i12.Future<_i7.GroupsResponse>);

  @override
  _i12.Future<_i7.GroupsResponse> updateGroup({
    required _i19.GroupRequest? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateGroup, [], {#body: body}),
            returnValue: _i12.Future<_i7.GroupsResponse>.value(
              _FakeGroupsResponse_25(
                this,
                Invocation.method(#updateGroup, [], {#body: body}),
              ),
            ),
          )
          as _i12.Future<_i7.GroupsResponse>);

  @override
  _i12.Stream<_i7.GravityResponse> updateGravity() =>
      (super.noSuchMethod(
            Invocation.method(#updateGravity, []),
            returnValue: _i12.Stream<_i7.GravityResponse>.empty(),
          )
          as _i12.Stream<_i7.GravityResponse>);

  @override
  _i12.Future<_i7.MessagesResponse> getMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, []),
            returnValue: _i12.Future<_i7.MessagesResponse>.value(
              _FakeMessagesResponse_27(
                this,
                Invocation.method(#getMessages, []),
              ),
            ),
          )
          as _i12.Future<_i7.MessagesResponse>);

  @override
  _i12.Future<_i7.RemoveMessagesResponse> removeMessage({
    required String? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeMessage, [], {#id: id}),
            returnValue: _i12.Future<_i7.RemoveMessagesResponse>.value(
              _FakeRemoveMessagesResponse_28(
                this,
                Invocation.method(#removeMessage, [], {#id: id}),
              ),
            ),
          )
          as _i12.Future<_i7.RemoveMessagesResponse>);
}
