// Mocks generated by Mockito 5.4.6 from annotations
// in pi_hole_client/test/ut/providers/gravity_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:pi_hole_client/data/repositories/database_repository.dart'
    as _i14;
import 'package:pi_hole_client/data/repositories/gravity_repository.dart'
    as _i17;
import 'package:pi_hole_client/data/services/api/api_gateway_interface.dart'
    as _i11;
import 'package:pi_hole_client/data/services/api/shared/models/domain.dart'
    as _i19;
import 'package:pi_hole_client/data/services/api/shared/models/gateways.dart'
    as _i7;
import 'package:pi_hole_client/data/services/api/shared/models/groups.dart'
    as _i21;
import 'package:pi_hole_client/data/services/api/shared/models/query_status.dart'
    as _i9;
import 'package:pi_hole_client/data/services/api/shared/models/subscriptions.dart'
    as _i20;
import 'package:pi_hole_client/data/services/api/v6/api_gateway_v6.dart'
    as _i18;
import 'package:pi_hole_client/data/services/api/v6/models/config/config.dart'
    as _i22;
import 'package:pi_hole_client/domain/models/database.dart' as _i3;
import 'package:pi_hole_client/domain/models/server.dart' as _i5;
import 'package:pi_hole_client/ui/core/themes/theme.dart' as _i2;
import 'package:pi_hole_client/ui/core/viewmodel/app_config_provider.dart'
    as _i10;
import 'package:pi_hole_client/ui/core/viewmodel/servers_provider.dart' as _i8;
import 'package:result_dart/result_dart.dart' as _i15;
import 'package:sqflite/sqflite.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppColors_0 extends _i1.SmartFake implements _i2.AppColors {
  _FakeAppColors_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppDbData_1 extends _i1.SmartFake implements _i3.AppDbData {
  _FakeAppDbData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_2 extends _i1.SmartFake implements _i4.Database {
  _FakeDatabase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServer_3 extends _i1.SmartFake implements _i5.Server {
  _FakeServer_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_4 extends _i1.SmartFake implements _i6.Response {
  _FakeResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_5 extends _i1.SmartFake
    implements _i6.StreamedResponse {
  _FakeStreamedResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginQueryResponse_6 extends _i1.SmartFake
    implements _i7.LoginQueryResponse {
  _FakeLoginQueryResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeStatusResponse_7 extends _i1.SmartFake
    implements _i7.RealtimeStatusResponse {
  _FakeRealtimeStatusResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDisableServerResponse_8 extends _i1.SmartFake
    implements _i7.DisableServerResponse {
  _FakeDisableServerResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEnableServerResponse_9 extends _i1.SmartFake
    implements _i7.EnableServerResponse {
  _FakeEnableServerResponse_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFetchOverTimeDataResponse_10 extends _i1.SmartFake
    implements _i7.FetchOverTimeDataResponse {
  _FakeFetchOverTimeDataResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFetchLogsResponse_11 extends _i1.SmartFake
    implements _i7.FetchLogsResponse {
  _FakeFetchLogsResponse_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSetWhiteBlacklistResponse_12 extends _i1.SmartFake
    implements _i7.SetWhiteBlacklistResponse {
  _FakeSetWhiteBlacklistResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetDomainLists_13 extends _i1.SmartFake
    implements _i7.GetDomainLists {
  _FakeGetDomainLists_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveDomainFromListResponse_14 extends _i1.SmartFake
    implements _i7.RemoveDomainFromListResponse {
  _FakeRemoveDomainFromListResponse_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddDomainToListResponse_15 extends _i1.SmartFake
    implements _i7.AddDomainToListResponse {
  _FakeAddDomainToListResponse_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDomainResponse_16 extends _i1.SmartFake
    implements _i7.DomainResponse {
  _FakeDomainResponse_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHostResponse_17 extends _i1.SmartFake implements _i7.HostResponse {
  _FakeHostResponse_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSensorsResponse_18 extends _i1.SmartFake
    implements _i7.SensorsResponse {
  _FakeSensorsResponse_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSystemResponse_19 extends _i1.SmartFake
    implements _i7.SystemResponse {
  _FakeSystemResponse_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVersionResponse_20 extends _i1.SmartFake
    implements _i7.VersionResponse {
  _FakeVersionResponse_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePiHoleServerInfoResponse_21 extends _i1.SmartFake
    implements _i7.PiHoleServerInfoResponse {
  _FakePiHoleServerInfoResponse_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubscriptionsResponse_22 extends _i1.SmartFake
    implements _i7.SubscriptionsResponse {
  _FakeSubscriptionsResponse_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveSubscriptionResponse_23 extends _i1.SmartFake
    implements _i7.RemoveSubscriptionResponse {
  _FakeRemoveSubscriptionResponse_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchResponse_24 extends _i1.SmartFake
    implements _i7.SearchResponse {
  _FakeSearchResponse_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGroupsResponse_25 extends _i1.SmartFake
    implements _i7.GroupsResponse {
  _FakeGroupsResponse_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveGroupResponse_26 extends _i1.SmartFake
    implements _i7.RemoveGroupResponse {
  _FakeRemoveGroupResponse_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessagesResponse_27 extends _i1.SmartFake
    implements _i7.MessagesResponse {
  _FakeMessagesResponse_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveMessageResponse_28 extends _i1.SmartFake
    implements _i7.RemoveMessageResponse {
  _FakeRemoveMessageResponse_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMetricsResponse_29 extends _i1.SmartFake
    implements _i7.MetricsResponse {
  _FakeMetricsResponse_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGatewayResponse_30 extends _i1.SmartFake
    implements _i7.GatewayResponse {
  _FakeGatewayResponse_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDevicesResponse_31 extends _i1.SmartFake
    implements _i7.DevicesResponse {
  _FakeDevicesResponse_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteDeviceResponse_32 extends _i1.SmartFake
    implements _i7.DeleteDeviceResponse {
  _FakeDeleteDeviceResponse_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfigurationResponse_33 extends _i1.SmartFake
    implements _i7.ConfigurationResponse {
  _FakeConfigurationResponse_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActionResponse_34 extends _i1.SmartFake
    implements _i7.ActionResponse {
  _FakeActionResponse_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSessionsResponse_35 extends _i1.SmartFake
    implements _i7.SessionsResponse {
  _FakeSessionsResponse_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteSessionResponse_36 extends _i1.SmartFake
    implements _i7.DeleteSessionResponse {
  _FakeDeleteSessionResponse_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientResponse_37 extends _i1.SmartFake
    implements _i7.ClientResponse {
  _FakeClientResponse_37(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDhcpResponse_38 extends _i1.SmartFake implements _i7.DhcpResponse {
  _FakeDhcpResponse_38(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteDhcpResponse_39 extends _i1.SmartFake
    implements _i7.DeleteDhcpResponse {
  _FakeDeleteDhcpResponse_39(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ServersProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockServersProvider extends _i1.Mock implements _i8.ServersProvider {
  MockServersProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppColors get colors => (super.noSuchMethod(
        Invocation.getter(#colors),
        returnValue: _FakeAppColors_0(
          this,
          Invocation.getter(#colors),
        ),
      ) as _i2.AppColors);

  @override
  List<_i5.Server> get getServersList => (super.noSuchMethod(
        Invocation.getter(#getServersList),
        returnValue: <_i5.Server>[],
      ) as List<_i5.Server>);

  @override
  int get numShown => (super.noSuchMethod(
        Invocation.getter(#numShown),
        returnValue: 0,
      ) as int);

  @override
  List<_i9.QueryStatus> get queryStatuses => (super.noSuchMethod(
        Invocation.getter(#queryStatuses),
        returnValue: <_i9.QueryStatus>[],
      ) as List<_i9.QueryStatus>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void update(_i10.AppConfigProvider? provider) => super.noSuchMethod(
        Invocation.method(
          #update,
          [provider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setConnectingServer(_i5.Server? server) => super.noSuchMethod(
        Invocation.method(
          #setConnectingServer,
          [server],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearConnectingServer() => super.noSuchMethod(
        Invocation.method(
          #clearConnectingServer,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.ApiGateway? loadApiGateway(_i5.Server? server) =>
      (super.noSuchMethod(Invocation.method(
        #loadApiGateway,
        [server],
      )) as _i11.ApiGateway?);

  @override
  _i11.ApiGateway? createApiGateway(_i5.Server? server) =>
      (super.noSuchMethod(Invocation.method(
        #createApiGateway,
        [server],
      )) as _i11.ApiGateway?);

  @override
  _i9.QueryStatus? getQueryStatus(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getQueryStatus,
        [key],
      )) as _i9.QueryStatus?);

  @override
  _i9.QueryStatus? findQueryStatus(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #findQueryStatus,
        [key],
      )) as _i9.QueryStatus?);

  @override
  _i12.Future<bool> addServer(_i5.Server? server) => (super.noSuchMethod(
        Invocation.method(
          #addServer,
          [server],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> editServer(_i5.Server? server) => (super.noSuchMethod(
        Invocation.method(
          #editServer,
          [server],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> removeServer(String? serverAddress) => (super.noSuchMethod(
        Invocation.method(
          #removeServer,
          [serverAddress],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> setDefaultServer(_i5.Server? server) => (super.noSuchMethod(
        Invocation.method(
          #setDefaultServer,
          [server],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<dynamic> saveFromDb(List<_i3.ServerDbData>? servers) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFromDb,
          [servers],
        ),
        returnValue: _i12.Future<dynamic>.value(),
      ) as _i12.Future<dynamic>);

  @override
  _i12.FutureOr<Map<String, dynamic>> checkUrlExists(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkUrlExists,
          [url],
        ),
        returnValue:
            _i12.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i12.FutureOr<Map<String, dynamic>>);

  @override
  void setselectedServer({
    required _i5.Server? server,
    bool? toHomeTab,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setselectedServer,
          [],
          {
            #server: server,
            #toHomeTab: toHomeTab,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateselectedServerStatus(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #updateselectedServerStatus,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<bool> deleteDbData() => (super.noSuchMethod(
        Invocation.method(
          #deleteDbData,
          [],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> resetSelectedServer() => (super.noSuchMethod(
        Invocation.method(
          #resetSelectedServer,
          [],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DatabaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseRepository extends _i1.Mock
    implements _i14.DatabaseRepository {
  MockDatabaseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.ServerDbData> get servers => (super.noSuchMethod(
        Invocation.getter(#servers),
        returnValue: <_i3.ServerDbData>[],
      ) as List<_i3.ServerDbData>);

  @override
  _i3.AppDbData get appConfig => (super.noSuchMethod(
        Invocation.getter(#appConfig),
        returnValue: _FakeAppDbData_1(
          this,
          Invocation.getter(#appConfig),
        ),
      ) as _i3.AppDbData);

  @override
  _i4.Database get dbInstance => (super.noSuchMethod(
        Invocation.getter(#dbInstance),
        returnValue: _FakeDatabase_2(
          this,
          Invocation.getter(#dbInstance),
        ),
      ) as _i4.Database);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> initialize() =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<bool> closeDb() => (super.noSuchMethod(
        Invocation.method(
          #closeDb,
          [],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> saveServerQuery(
          _i5.Server? server) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveServerQuery,
          [server],
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveServerQuery,
            [server],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> editServerQuery(
          _i5.Server? server) =>
      (super.noSuchMethod(
        Invocation.method(
          #editServerQuery,
          [server],
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #editServerQuery,
            [server],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> setDefaultServerQuery(
          String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDefaultServerQuery,
          [url],
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #setDefaultServerQuery,
            [url],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> removeServerQuery(
    String? address, {
    _i4.Transaction? txn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeServerQuery,
          [address],
          {#txn: txn},
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #removeServerQuery,
            [address],
            {#txn: txn},
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> deleteServersDataQuery(
          {_i4.Transaction? txn}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteServersDataQuery,
          [],
          {#txn: txn},
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #deleteServersDataQuery,
            [],
            {#txn: txn},
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<bool, Exception>> checkUrlExistsQuery(
          String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkUrlExistsQuery,
          [url],
        ),
        returnValue: _i12.Future<_i15.ResultDart<bool, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<bool, Exception>>(
          this,
          Invocation.method(
            #checkUrlExistsQuery,
            [url],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<bool, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> updateConfigQuery({
    required String? column,
    required Object? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConfigQuery,
          [],
          {
            #column: column,
            #value: value,
          },
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #updateConfigQuery,
            [],
            {
              #column: column,
              #value: value,
            },
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> restoreAppConfigQuery() =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreAppConfigQuery,
          [],
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #restoreAppConfigQuery,
            [],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> cleanUpSecureStorage() =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanUpSecureStorage,
          [],
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #cleanUpSecureStorage,
            [],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<
      _i15.ResultDart<_i3.GravityUpdateData, Exception>> getGravityUpdateQuery(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGravityUpdateQuery,
          [address],
        ),
        returnValue: _i12
            .Future<_i15.ResultDart<_i3.GravityUpdateData, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<_i3.GravityUpdateData, Exception>>(
          this,
          Invocation.method(
            #getGravityUpdateQuery,
            [address],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<_i3.GravityUpdateData, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> upsertGravityUpdateQuery(
          _i3.GravityUpdateData? gravityUpdateData) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertGravityUpdateQuery,
          [gravityUpdateData],
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #upsertGravityUpdateQuery,
            [gravityUpdateData],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> removeGravityUpdateQuery(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeGravityUpdateQuery,
          [address],
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #removeGravityUpdateQuery,
            [address],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<
      _i15.ResultDart<List<_i3.GravityLogData>, Exception>> getGravityLogsQuery(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGravityLogsQuery,
          [address],
        ),
        returnValue: _i12
            .Future<_i15.ResultDart<List<_i3.GravityLogData>, Exception>>.value(
            _i16.dummyValue<
                _i15.ResultDart<List<_i3.GravityLogData>, Exception>>(
          this,
          Invocation.method(
            #getGravityLogsQuery,
            [address],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<List<_i3.GravityLogData>, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> insertGravityLogQuery(
          List<_i3.GravityLogData>? gravityLogsDataList) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertGravityLogQuery,
          [gravityLogsDataList],
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #insertGravityLogQuery,
            [gravityLogsDataList],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> clearGravityLogsQuery(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearGravityLogsQuery,
          [address],
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #clearGravityLogsQuery,
            [address],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<List<_i3.GravityMessageData>, Exception>>
      getGravityMessagesQuery(String? address) => (super.noSuchMethod(
            Invocation.method(
              #getGravityMessagesQuery,
              [address],
            ),
            returnValue: _i12.Future<
                    _i15
                    .ResultDart<List<_i3.GravityMessageData>, Exception>>.value(
                _i16.dummyValue<
                    _i15.ResultDart<List<_i3.GravityMessageData>, Exception>>(
              this,
              Invocation.method(
                #getGravityMessagesQuery,
                [address],
              ),
            )),
          ) as _i12.Future<
              _i15.ResultDart<List<_i3.GravityMessageData>, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> insertGravityMessageQuery(
          List<_i3.GravityMessageData>? messagesList) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertGravityMessageQuery,
          [messagesList],
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #insertGravityMessageQuery,
            [messagesList],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> clearGravityMessagesQuery(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearGravityMessagesQuery,
          [address],
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #clearGravityMessagesQuery,
            [address],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<_i3.GravityData, Exception>> getGravityDataQuery(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGravityDataQuery,
          [address],
        ),
        returnValue:
            _i12.Future<_i15.ResultDart<_i3.GravityData, Exception>>.value(
                _i16.dummyValue<_i15.ResultDart<_i3.GravityData, Exception>>(
          this,
          Invocation.method(
            #getGravityDataQuery,
            [address],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<_i3.GravityData, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> clearGravityDataQuery(
    String? address, {
    _i4.Transaction? txn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearGravityDataQuery,
          [address],
          {#txn: txn},
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #clearGravityDataQuery,
            [address],
            {#txn: txn},
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> clearAllGravityDataQuery(
          {_i4.Transaction? txn}) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearAllGravityDataQuery,
          [],
          {#txn: txn},
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #clearAllGravityDataQuery,
            [],
            {#txn: txn},
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<void, Exception>> deleteMessageQuery(
    String? address,
    int? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessageQuery,
          [
            address,
            id,
          ],
        ),
        returnValue: _i12.Future<_i15.ResultDart<void, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #deleteMessageQuery,
            [
              address,
              id,
            ],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<void, Exception>>);
}

/// A class which mocks [GravityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGravityRepository extends _i1.Mock implements _i17.GravityRepository {
  MockGravityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<
      _i15.ResultDart<_i3.GravityUpdateData, Exception>> fetchGravityUpdate(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGravityUpdate,
          [address],
        ),
        returnValue: _i12
            .Future<_i15.ResultDart<_i3.GravityUpdateData, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<_i3.GravityUpdateData, Exception>>(
          this,
          Invocation.method(
            #fetchGravityUpdate,
            [address],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<_i3.GravityUpdateData, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<int, Exception>> upsertGravityUpdate(
          _i3.GravityUpdateData? gravityUpdateData) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertGravityUpdate,
          [gravityUpdateData],
        ),
        returnValue: _i12.Future<_i15.ResultDart<int, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<int, Exception>>(
          this,
          Invocation.method(
            #upsertGravityUpdate,
            [gravityUpdateData],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<int, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<int, Exception>> deleteGravityUpdate(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteGravityUpdate,
          [address],
        ),
        returnValue: _i12.Future<_i15.ResultDart<int, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<int, Exception>>(
          this,
          Invocation.method(
            #deleteGravityUpdate,
            [address],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<int, Exception>>);

  @override
  _i12.Future<
      _i15.ResultDart<List<_i3.GravityLogData>, Exception>> fetchGravityLogs(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGravityLogs,
          [address],
        ),
        returnValue: _i12
            .Future<_i15.ResultDart<List<_i3.GravityLogData>, Exception>>.value(
            _i16.dummyValue<
                _i15.ResultDart<List<_i3.GravityLogData>, Exception>>(
          this,
          Invocation.method(
            #fetchGravityLogs,
            [address],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<List<_i3.GravityLogData>, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<int, Exception>> insertGravityLogs(
          List<_i3.GravityLogData>? gravityLogsDataList) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertGravityLogs,
          [gravityLogsDataList],
        ),
        returnValue: _i12.Future<_i15.ResultDart<int, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<int, Exception>>(
          this,
          Invocation.method(
            #insertGravityLogs,
            [gravityLogsDataList],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<int, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<int, Exception>> deleteGravityLogs(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteGravityLogs,
          [address],
        ),
        returnValue: _i12.Future<_i15.ResultDart<int, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<int, Exception>>(
          this,
          Invocation.method(
            #deleteGravityLogs,
            [address],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<int, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<List<_i3.GravityMessageData>, Exception>>
      fetchGravityMessages(String? address) => (super.noSuchMethod(
            Invocation.method(
              #fetchGravityMessages,
              [address],
            ),
            returnValue: _i12.Future<
                    _i15
                    .ResultDart<List<_i3.GravityMessageData>, Exception>>.value(
                _i16.dummyValue<
                    _i15.ResultDart<List<_i3.GravityMessageData>, Exception>>(
              this,
              Invocation.method(
                #fetchGravityMessages,
                [address],
              ),
            )),
          ) as _i12.Future<
              _i15.ResultDart<List<_i3.GravityMessageData>, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<int, Exception>> insertGravityMessages(
          List<_i3.GravityMessageData>? messagesList) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertGravityMessages,
          [messagesList],
        ),
        returnValue: _i12.Future<_i15.ResultDart<int, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<int, Exception>>(
          this,
          Invocation.method(
            #insertGravityMessages,
            [messagesList],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<int, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<int, Exception>> deleteGravityMessages(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteGravityMessages,
          [address],
        ),
        returnValue: _i12.Future<_i15.ResultDart<int, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<int, Exception>>(
          this,
          Invocation.method(
            #deleteGravityMessages,
            [address],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<int, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<int, Exception>> deleteGravityMessage(
    String? address,
    int? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteGravityMessage,
          [
            address,
            id,
          ],
        ),
        returnValue: _i12.Future<_i15.ResultDart<int, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<int, Exception>>(
          this,
          Invocation.method(
            #deleteGravityMessage,
            [
              address,
              id,
            ],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<int, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<_i3.GravityData, Exception>> fetchGravityData(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGravityData,
          [address],
        ),
        returnValue:
            _i12.Future<_i15.ResultDart<_i3.GravityData, Exception>>.value(
                _i16.dummyValue<_i15.ResultDart<_i3.GravityData, Exception>>(
          this,
          Invocation.method(
            #fetchGravityData,
            [address],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<_i3.GravityData, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<int, Exception>> deleteGravityData(
          String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteGravityData,
          [address],
        ),
        returnValue: _i12.Future<_i15.ResultDart<int, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<int, Exception>>(
          this,
          Invocation.method(
            #deleteGravityData,
            [address],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<int, Exception>>);

  @override
  _i12.Future<_i15.ResultDart<int, Exception>> deleteAllGravityData() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllGravityData,
          [],
        ),
        returnValue: _i12.Future<_i15.ResultDart<int, Exception>>.value(
            _i16.dummyValue<_i15.ResultDart<int, Exception>>(
          this,
          Invocation.method(
            #deleteAllGravityData,
            [],
          ),
        )),
      ) as _i12.Future<_i15.ResultDart<int, Exception>>);
}

/// A class which mocks [ApiGatewayV6].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiGatewayV6 extends _i1.Mock implements _i18.ApiGatewayV6 {
  MockApiGatewayV6() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get unexpectedError => (super.noSuchMethod(
        Invocation.getter(#unexpectedError),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#unexpectedError),
        ),
      ) as String);

  @override
  String get fetchError => (super.noSuchMethod(
        Invocation.getter(#fetchError),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#fetchError),
        ),
      ) as String);

  @override
  String get notImplementedError => (super.noSuchMethod(
        Invocation.getter(#notImplementedError),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#notImplementedError),
        ),
      ) as String);

  @override
  String get postError => (super.noSuchMethod(
        Invocation.getter(#postError),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#postError),
        ),
      ) as String);

  @override
  String get deleteError => (super.noSuchMethod(
        Invocation.getter(#deleteError),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#deleteError),
        ),
      ) as String);

  @override
  _i5.Server get server => (super.noSuchMethod(
        Invocation.getter(#server),
        returnValue: _FakeServer_3(
          this,
          Invocation.getter(#server),
        ),
      ) as _i5.Server);

  @override
  _i12.Future<_i6.Response> httpClient({
    required String? method,
    required String? url,
    Map<String, String>? headers,
    Map<String, dynamic>? body,
    int? timeout = 10,
    int? maxRetries = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #httpClient,
          [],
          {
            #method: method,
            #url: url,
            #headers: headers,
            #body: body,
            #timeout: timeout,
            #maxRetries: maxRetries,
          },
        ),
        returnValue: _i12.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #httpClient,
            [],
            {
              #method: method,
              #url: url,
              #headers: headers,
              #body: body,
              #timeout: timeout,
              #maxRetries: maxRetries,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response>);

  @override
  _i12.Future<_i6.StreamedResponse> httpClientStream({
    required String? method,
    required String? url,
    Map<String, String>? headers,
    Map<String, dynamic>? body,
    int? timeout = 10,
    int? maxRetries = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #httpClientStream,
          [],
          {
            #method: method,
            #url: url,
            #headers: headers,
            #body: body,
            #timeout: timeout,
            #maxRetries: maxRetries,
          },
        ),
        returnValue:
            _i12.Future<_i6.StreamedResponse>.value(_FakeStreamedResponse_5(
          this,
          Invocation.method(
            #httpClientStream,
            [],
            {
              #method: method,
              #url: url,
              #headers: headers,
              #body: body,
              #timeout: timeout,
              #maxRetries: maxRetries,
            },
          ),
        )),
      ) as _i12.Future<_i6.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i7.LoginQueryResponse> loginQuery({bool? refresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginQuery,
          [],
          {#refresh: refresh},
        ),
        returnValue:
            _i12.Future<_i7.LoginQueryResponse>.value(_FakeLoginQueryResponse_6(
          this,
          Invocation.method(
            #loginQuery,
            [],
            {#refresh: refresh},
          ),
        )),
      ) as _i12.Future<_i7.LoginQueryResponse>);

  @override
  _i12.Future<_i7.RealtimeStatusResponse> realtimeStatus({int? clientCount}) =>
      (super.noSuchMethod(
        Invocation.method(
          #realtimeStatus,
          [],
          {#clientCount: clientCount},
        ),
        returnValue: _i12.Future<_i7.RealtimeStatusResponse>.value(
            _FakeRealtimeStatusResponse_7(
          this,
          Invocation.method(
            #realtimeStatus,
            [],
            {#clientCount: clientCount},
          ),
        )),
      ) as _i12.Future<_i7.RealtimeStatusResponse>);

  @override
  _i12.Future<_i7.DisableServerResponse> disableServerRequest(int? time) =>
      (super.noSuchMethod(
        Invocation.method(
          #disableServerRequest,
          [time],
        ),
        returnValue: _i12.Future<_i7.DisableServerResponse>.value(
            _FakeDisableServerResponse_8(
          this,
          Invocation.method(
            #disableServerRequest,
            [time],
          ),
        )),
      ) as _i12.Future<_i7.DisableServerResponse>);

  @override
  _i12.Future<_i7.EnableServerResponse> enableServerRequest() =>
      (super.noSuchMethod(
        Invocation.method(
          #enableServerRequest,
          [],
        ),
        returnValue: _i12.Future<_i7.EnableServerResponse>.value(
            _FakeEnableServerResponse_9(
          this,
          Invocation.method(
            #enableServerRequest,
            [],
          ),
        )),
      ) as _i12.Future<_i7.EnableServerResponse>);

  @override
  _i12.Future<_i7.FetchOverTimeDataResponse> fetchOverTimeData(
          {int? clientCount}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchOverTimeData,
          [],
          {#clientCount: clientCount},
        ),
        returnValue: _i12.Future<_i7.FetchOverTimeDataResponse>.value(
            _FakeFetchOverTimeDataResponse_10(
          this,
          Invocation.method(
            #fetchOverTimeData,
            [],
            {#clientCount: clientCount},
          ),
        )),
      ) as _i12.Future<_i7.FetchOverTimeDataResponse>);

  @override
  _i12.Future<_i7.FetchLogsResponse> fetchLogs(
    DateTime? from,
    DateTime? until, {
    int? size,
    int? cursor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLogs,
          [
            from,
            until,
          ],
          {
            #size: size,
            #cursor: cursor,
          },
        ),
        returnValue:
            _i12.Future<_i7.FetchLogsResponse>.value(_FakeFetchLogsResponse_11(
          this,
          Invocation.method(
            #fetchLogs,
            [
              from,
              until,
            ],
            {
              #size: size,
              #cursor: cursor,
            },
          ),
        )),
      ) as _i12.Future<_i7.FetchLogsResponse>);

  @override
  _i12.Future<_i7.SetWhiteBlacklistResponse> setWhiteBlacklist(
    String? domain,
    String? list,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWhiteBlacklist,
          [
            domain,
            list,
          ],
        ),
        returnValue: _i12.Future<_i7.SetWhiteBlacklistResponse>.value(
            _FakeSetWhiteBlacklistResponse_12(
          this,
          Invocation.method(
            #setWhiteBlacklist,
            [
              domain,
              list,
            ],
          ),
        )),
      ) as _i12.Future<_i7.SetWhiteBlacklistResponse>);

  @override
  _i12.Future<_i7.GetDomainLists> getDomainLists() => (super.noSuchMethod(
        Invocation.method(
          #getDomainLists,
          [],
        ),
        returnValue:
            _i12.Future<_i7.GetDomainLists>.value(_FakeGetDomainLists_13(
          this,
          Invocation.method(
            #getDomainLists,
            [],
          ),
        )),
      ) as _i12.Future<_i7.GetDomainLists>);

  @override
  _i12.Future<_i7.RemoveDomainFromListResponse> removeDomainFromList(
          _i19.Domain? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeDomainFromList,
          [domain],
        ),
        returnValue: _i12.Future<_i7.RemoveDomainFromListResponse>.value(
            _FakeRemoveDomainFromListResponse_14(
          this,
          Invocation.method(
            #removeDomainFromList,
            [domain],
          ),
        )),
      ) as _i12.Future<_i7.RemoveDomainFromListResponse>);

  @override
  _i12.Future<_i7.AddDomainToListResponse> addDomainToList(
          Map<String, dynamic>? domainData) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDomainToList,
          [domainData],
        ),
        returnValue: _i12.Future<_i7.AddDomainToListResponse>.value(
            _FakeAddDomainToListResponse_15(
          this,
          Invocation.method(
            #addDomainToList,
            [domainData],
          ),
        )),
      ) as _i12.Future<_i7.AddDomainToListResponse>);

  @override
  _i12.Future<_i7.DomainResponse> updateDomain(
          {required _i19.DomainRequest? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDomain,
          [],
          {#body: body},
        ),
        returnValue:
            _i12.Future<_i7.DomainResponse>.value(_FakeDomainResponse_16(
          this,
          Invocation.method(
            #updateDomain,
            [],
            {#body: body},
          ),
        )),
      ) as _i12.Future<_i7.DomainResponse>);

  @override
  _i12.Future<_i7.HostResponse> fetchHostInfo() => (super.noSuchMethod(
        Invocation.method(
          #fetchHostInfo,
          [],
        ),
        returnValue: _i12.Future<_i7.HostResponse>.value(_FakeHostResponse_17(
          this,
          Invocation.method(
            #fetchHostInfo,
            [],
          ),
        )),
      ) as _i12.Future<_i7.HostResponse>);

  @override
  _i12.Future<_i7.SensorsResponse> fetchSensorsInfo() => (super.noSuchMethod(
        Invocation.method(
          #fetchSensorsInfo,
          [],
        ),
        returnValue:
            _i12.Future<_i7.SensorsResponse>.value(_FakeSensorsResponse_18(
          this,
          Invocation.method(
            #fetchSensorsInfo,
            [],
          ),
        )),
      ) as _i12.Future<_i7.SensorsResponse>);

  @override
  _i12.Future<_i7.SystemResponse> fetchSystemInfo() => (super.noSuchMethod(
        Invocation.method(
          #fetchSystemInfo,
          [],
        ),
        returnValue:
            _i12.Future<_i7.SystemResponse>.value(_FakeSystemResponse_19(
          this,
          Invocation.method(
            #fetchSystemInfo,
            [],
          ),
        )),
      ) as _i12.Future<_i7.SystemResponse>);

  @override
  _i12.Future<_i7.VersionResponse> fetchVersionInfo() => (super.noSuchMethod(
        Invocation.method(
          #fetchVersionInfo,
          [],
        ),
        returnValue:
            _i12.Future<_i7.VersionResponse>.value(_FakeVersionResponse_20(
          this,
          Invocation.method(
            #fetchVersionInfo,
            [],
          ),
        )),
      ) as _i12.Future<_i7.VersionResponse>);

  @override
  _i12.Future<_i7.PiHoleServerInfoResponse> fetchAllServerInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllServerInfo,
          [],
        ),
        returnValue: _i12.Future<_i7.PiHoleServerInfoResponse>.value(
            _FakePiHoleServerInfoResponse_21(
          this,
          Invocation.method(
            #fetchAllServerInfo,
            [],
          ),
        )),
      ) as _i12.Future<_i7.PiHoleServerInfoResponse>);

  @override
  _i12.Future<_i7.SubscriptionsResponse> getSubscriptions({
    String? url,
    String? stype,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubscriptions,
          [],
          {
            #url: url,
            #stype: stype,
          },
        ),
        returnValue: _i12.Future<_i7.SubscriptionsResponse>.value(
            _FakeSubscriptionsResponse_22(
          this,
          Invocation.method(
            #getSubscriptions,
            [],
            {
              #url: url,
              #stype: stype,
            },
          ),
        )),
      ) as _i12.Future<_i7.SubscriptionsResponse>);

  @override
  _i12.Future<_i7.RemoveSubscriptionResponse> removeSubscription({
    required String? url,
    String? stype,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeSubscription,
          [],
          {
            #url: url,
            #stype: stype,
          },
        ),
        returnValue: _i12.Future<_i7.RemoveSubscriptionResponse>.value(
            _FakeRemoveSubscriptionResponse_23(
          this,
          Invocation.method(
            #removeSubscription,
            [],
            {
              #url: url,
              #stype: stype,
            },
          ),
        )),
      ) as _i12.Future<_i7.RemoveSubscriptionResponse>);

  @override
  _i12.Future<_i7.SubscriptionsResponse> createSubscription(
          {required _i20.SubscriptionRequest? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSubscription,
          [],
          {#body: body},
        ),
        returnValue: _i12.Future<_i7.SubscriptionsResponse>.value(
            _FakeSubscriptionsResponse_22(
          this,
          Invocation.method(
            #createSubscription,
            [],
            {#body: body},
          ),
        )),
      ) as _i12.Future<_i7.SubscriptionsResponse>);

  @override
  _i12.Future<_i7.SubscriptionsResponse> updateSubscription(
          {required _i20.SubscriptionRequest? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSubscription,
          [],
          {#body: body},
        ),
        returnValue: _i12.Future<_i7.SubscriptionsResponse>.value(
            _FakeSubscriptionsResponse_22(
          this,
          Invocation.method(
            #updateSubscription,
            [],
            {#body: body},
          ),
        )),
      ) as _i12.Future<_i7.SubscriptionsResponse>);

  @override
  _i12.Future<_i7.SearchResponse> searchSubscriptions({
    required String? domain,
    bool? partial,
    int? limit,
    bool? debug,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchSubscriptions,
          [],
          {
            #domain: domain,
            #partial: partial,
            #limit: limit,
            #debug: debug,
          },
        ),
        returnValue:
            _i12.Future<_i7.SearchResponse>.value(_FakeSearchResponse_24(
          this,
          Invocation.method(
            #searchSubscriptions,
            [],
            {
              #domain: domain,
              #partial: partial,
              #limit: limit,
              #debug: debug,
            },
          ),
        )),
      ) as _i12.Future<_i7.SearchResponse>);

  @override
  _i12.Future<_i7.GroupsResponse> getGroups({String? name}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroups,
          [],
          {#name: name},
        ),
        returnValue:
            _i12.Future<_i7.GroupsResponse>.value(_FakeGroupsResponse_25(
          this,
          Invocation.method(
            #getGroups,
            [],
            {#name: name},
          ),
        )),
      ) as _i12.Future<_i7.GroupsResponse>);

  @override
  _i12.Future<_i7.RemoveGroupResponse> removeGroup({required String? name}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeGroup,
          [],
          {#name: name},
        ),
        returnValue: _i12.Future<_i7.RemoveGroupResponse>.value(
            _FakeRemoveGroupResponse_26(
          this,
          Invocation.method(
            #removeGroup,
            [],
            {#name: name},
          ),
        )),
      ) as _i12.Future<_i7.RemoveGroupResponse>);

  @override
  _i12.Future<_i7.GroupsResponse> createGroup(
          {required _i21.GroupRequest? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGroup,
          [],
          {#body: body},
        ),
        returnValue:
            _i12.Future<_i7.GroupsResponse>.value(_FakeGroupsResponse_25(
          this,
          Invocation.method(
            #createGroup,
            [],
            {#body: body},
          ),
        )),
      ) as _i12.Future<_i7.GroupsResponse>);

  @override
  _i12.Future<_i7.GroupsResponse> updateGroup(
          {required _i21.GroupRequest? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGroup,
          [],
          {#body: body},
        ),
        returnValue:
            _i12.Future<_i7.GroupsResponse>.value(_FakeGroupsResponse_25(
          this,
          Invocation.method(
            #updateGroup,
            [],
            {#body: body},
          ),
        )),
      ) as _i12.Future<_i7.GroupsResponse>);

  @override
  _i12.Stream<_i7.GravityResponse> updateGravity() => (super.noSuchMethod(
        Invocation.method(
          #updateGravity,
          [],
        ),
        returnValue: _i12.Stream<_i7.GravityResponse>.empty(),
      ) as _i12.Stream<_i7.GravityResponse>);

  @override
  _i12.Future<_i7.MessagesResponse> getMessages() => (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [],
        ),
        returnValue:
            _i12.Future<_i7.MessagesResponse>.value(_FakeMessagesResponse_27(
          this,
          Invocation.method(
            #getMessages,
            [],
          ),
        )),
      ) as _i12.Future<_i7.MessagesResponse>);

  @override
  _i12.Future<_i7.RemoveMessageResponse> removeMessage(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMessage,
          [id],
        ),
        returnValue: _i12.Future<_i7.RemoveMessageResponse>.value(
            _FakeRemoveMessageResponse_28(
          this,
          Invocation.method(
            #removeMessage,
            [id],
          ),
        )),
      ) as _i12.Future<_i7.RemoveMessageResponse>);

  @override
  _i12.Future<_i7.MetricsResponse> getMetrics() => (super.noSuchMethod(
        Invocation.method(
          #getMetrics,
          [],
        ),
        returnValue:
            _i12.Future<_i7.MetricsResponse>.value(_FakeMetricsResponse_29(
          this,
          Invocation.method(
            #getMetrics,
            [],
          ),
        )),
      ) as _i12.Future<_i7.MetricsResponse>);

  @override
  _i12.Future<_i7.GatewayResponse> getGateway({bool? isDetailed}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGateway,
          [],
          {#isDetailed: isDetailed},
        ),
        returnValue:
            _i12.Future<_i7.GatewayResponse>.value(_FakeGatewayResponse_30(
          this,
          Invocation.method(
            #getGateway,
            [],
            {#isDetailed: isDetailed},
          ),
        )),
      ) as _i12.Future<_i7.GatewayResponse>);

  @override
  _i12.Future<_i7.DevicesResponse> getDevices({
    int? maxDevices,
    int? maxAddresses,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDevices,
          [],
          {
            #maxDevices: maxDevices,
            #maxAddresses: maxAddresses,
          },
        ),
        returnValue:
            _i12.Future<_i7.DevicesResponse>.value(_FakeDevicesResponse_31(
          this,
          Invocation.method(
            #getDevices,
            [],
            {
              #maxDevices: maxDevices,
              #maxAddresses: maxAddresses,
            },
          ),
        )),
      ) as _i12.Future<_i7.DevicesResponse>);

  @override
  _i12.Future<_i7.DeleteDeviceResponse> deleteDevice(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDevice,
          [id],
        ),
        returnValue: _i12.Future<_i7.DeleteDeviceResponse>.value(
            _FakeDeleteDeviceResponse_32(
          this,
          Invocation.method(
            #deleteDevice,
            [id],
          ),
        )),
      ) as _i12.Future<_i7.DeleteDeviceResponse>);

  @override
  _i12.Future<_i7.ConfigurationResponse> getConfiguration({
    String? element,
    bool? isDetailed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConfiguration,
          [],
          {
            #element: element,
            #isDetailed: isDetailed,
          },
        ),
        returnValue: _i12.Future<_i7.ConfigurationResponse>.value(
            _FakeConfigurationResponse_33(
          this,
          Invocation.method(
            #getConfiguration,
            [],
            {
              #element: element,
              #isDetailed: isDetailed,
            },
          ),
        )),
      ) as _i12.Future<_i7.ConfigurationResponse>);

  @override
  _i12.Future<_i7.ConfigurationResponse> patchConfiguration(
          _i22.ConfigData? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchConfiguration,
          [body],
        ),
        returnValue: _i12.Future<_i7.ConfigurationResponse>.value(
            _FakeConfigurationResponse_33(
          this,
          Invocation.method(
            #patchConfiguration,
            [body],
          ),
        )),
      ) as _i12.Future<_i7.ConfigurationResponse>);

  @override
  _i12.Future<_i7.ConfigurationResponse> patchDnsQueryLoggingConfig(
          bool? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchDnsQueryLoggingConfig,
          [status],
        ),
        returnValue: _i12.Future<_i7.ConfigurationResponse>.value(
            _FakeConfigurationResponse_33(
          this,
          Invocation.method(
            #patchDnsQueryLoggingConfig,
            [status],
          ),
        )),
      ) as _i12.Future<_i7.ConfigurationResponse>);

  @override
  _i12.Future<_i7.ActionResponse> flushArp() => (super.noSuchMethod(
        Invocation.method(
          #flushArp,
          [],
        ),
        returnValue:
            _i12.Future<_i7.ActionResponse>.value(_FakeActionResponse_34(
          this,
          Invocation.method(
            #flushArp,
            [],
          ),
        )),
      ) as _i12.Future<_i7.ActionResponse>);

  @override
  _i12.Future<_i7.ActionResponse> flushLogs() => (super.noSuchMethod(
        Invocation.method(
          #flushLogs,
          [],
        ),
        returnValue:
            _i12.Future<_i7.ActionResponse>.value(_FakeActionResponse_34(
          this,
          Invocation.method(
            #flushLogs,
            [],
          ),
        )),
      ) as _i12.Future<_i7.ActionResponse>);

  @override
  _i12.Future<_i7.ActionResponse> restartDns() => (super.noSuchMethod(
        Invocation.method(
          #restartDns,
          [],
        ),
        returnValue:
            _i12.Future<_i7.ActionResponse>.value(_FakeActionResponse_34(
          this,
          Invocation.method(
            #restartDns,
            [],
          ),
        )),
      ) as _i12.Future<_i7.ActionResponse>);

  @override
  _i12.Future<_i7.SessionsResponse> getSessions() => (super.noSuchMethod(
        Invocation.method(
          #getSessions,
          [],
        ),
        returnValue:
            _i12.Future<_i7.SessionsResponse>.value(_FakeSessionsResponse_35(
          this,
          Invocation.method(
            #getSessions,
            [],
          ),
        )),
      ) as _i12.Future<_i7.SessionsResponse>);

  @override
  _i12.Future<_i7.DeleteSessionResponse> deleteSession(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSession,
          [id],
        ),
        returnValue: _i12.Future<_i7.DeleteSessionResponse>.value(
            _FakeDeleteSessionResponse_36(
          this,
          Invocation.method(
            #deleteSession,
            [id],
          ),
        )),
      ) as _i12.Future<_i7.DeleteSessionResponse>);

  @override
  _i12.Future<_i7.ClientResponse> getClient() => (super.noSuchMethod(
        Invocation.method(
          #getClient,
          [],
        ),
        returnValue:
            _i12.Future<_i7.ClientResponse>.value(_FakeClientResponse_37(
          this,
          Invocation.method(
            #getClient,
            [],
          ),
        )),
      ) as _i12.Future<_i7.ClientResponse>);

  @override
  _i12.Future<_i7.DhcpResponse> getDhcps() => (super.noSuchMethod(
        Invocation.method(
          #getDhcps,
          [],
        ),
        returnValue: _i12.Future<_i7.DhcpResponse>.value(_FakeDhcpResponse_38(
          this,
          Invocation.method(
            #getDhcps,
            [],
          ),
        )),
      ) as _i12.Future<_i7.DhcpResponse>);

  @override
  _i12.Future<_i7.DeleteDhcpResponse> deleteDhcp(String? ip) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDhcp,
          [ip],
        ),
        returnValue: _i12.Future<_i7.DeleteDhcpResponse>.value(
            _FakeDeleteDhcpResponse_39(
          this,
          Invocation.method(
            #deleteDhcp,
            [ip],
          ),
        )),
      ) as _i12.Future<_i7.DeleteDhcpResponse>);
}
