// Mocks generated by Mockito 5.4.6 from annotations
// in pi_hole_client/test/ut/providers/local_dns_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:pi_hole_client/data/repositories/api/interfaces/local_dns_repository.dart'
    as _i2;
import 'package:pi_hole_client/data/repositories/api/interfaces/network_repository.dart'
    as _i7;
import 'package:pi_hole_client/domain/model/local_dns/local_dns.dart' as _i5;
import 'package:pi_hole_client/domain/model/network/network.dart' as _i8;
import 'package:result_dart/result_dart.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocalDnsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDnsRepository extends _i1.Mock
    implements _i2.LocalDnsRepository {
  MockLocalDnsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResultDart<List<_i5.LocalDns>, Exception>> fetchRecords() =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecords, []),
            returnValue:
                _i3.Future<_i4.ResultDart<List<_i5.LocalDns>, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<List<_i5.LocalDns>, Exception>>(
                    this,
                    Invocation.method(#fetchRecords, []),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<List<_i5.LocalDns>, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<_i4.Unit, Exception>> addRecord({
    required String? ip,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addRecord, [], {#ip: ip, #name: name}),
            returnValue: _i3.Future<_i4.ResultDart<_i4.Unit, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<_i4.Unit, Exception>>(
                this,
                Invocation.method(#addRecord, [], {#ip: ip, #name: name}),
              ),
            ),
          )
          as _i3.Future<_i4.ResultDart<_i4.Unit, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<_i4.Unit, Exception>> updateRecord({
    required _i5.LocalDns? record,
    required String? oldIp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecord, [], {
              #record: record,
              #oldIp: oldIp,
            }),
            returnValue: _i3.Future<_i4.ResultDart<_i4.Unit, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<_i4.Unit, Exception>>(
                this,
                Invocation.method(#updateRecord, [], {
                  #record: record,
                  #oldIp: oldIp,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ResultDart<_i4.Unit, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<_i4.Unit, Exception>> deleteRecord({
    required String? ip,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecord, [], {#ip: ip, #name: name}),
            returnValue: _i3.Future<_i4.ResultDart<_i4.Unit, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<_i4.Unit, Exception>>(
                this,
                Invocation.method(#deleteRecord, [], {#ip: ip, #name: name}),
              ),
            ),
          )
          as _i3.Future<_i4.ResultDart<_i4.Unit, Exception>>);
}

/// A class which mocks [NetworkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkRepository extends _i1.Mock implements _i7.NetworkRepository {
  MockNetworkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResultDart<List<_i8.Device>, Exception>> fetchDevices({
    int? maxDevices = 999,
    int? maxAddresses = 25,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDevices, [], {
              #maxDevices: maxDevices,
              #maxAddresses: maxAddresses,
            }),
            returnValue:
                _i3.Future<_i4.ResultDart<List<_i8.Device>, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<List<_i8.Device>, Exception>>(
                    this,
                    Invocation.method(#fetchDevices, [], {
                      #maxDevices: maxDevices,
                      #maxAddresses: maxAddresses,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<List<_i8.Device>, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<_i4.Unit, Exception>> deleteDevice(int? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDevice, [deviceId]),
            returnValue: _i3.Future<_i4.ResultDart<_i4.Unit, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<_i4.Unit, Exception>>(
                this,
                Invocation.method(#deleteDevice, [deviceId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultDart<_i4.Unit, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<_i8.Gateways, Exception>> fetchGateways({
    bool? isDetailed,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGateways, [], {#isDetailed: isDetailed}),
            returnValue:
                _i3.Future<_i4.ResultDart<_i8.Gateways, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<_i8.Gateways, Exception>>(
                    this,
                    Invocation.method(#fetchGateways, [], {
                      #isDetailed: isDetailed,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<_i8.Gateways, Exception>>);
}
