import 'package:pi_hole_client/data/model/v6/config/config.dart' as srv;
import 'package:pi_hole_client/domain/model/config/config.dart' as repo;

const kSrvJsonConfigData = {
  'config': {
    'dns': {
      'upstreams': ['127.0.0.1#5353', '8.8.8.8'],
      'CNAMEdeepInspect': true,
      'blockESNI': true,
      'EDNS0ECS': true,
      'ignoreLocalhost': false,
      'showDNSSEC': true,
      'analyzeOnlyAandAAAA': false,
      'piholePTR': 'PI.HOLE',
      'replyWhenBusy': 'ALLOW',
      'blockTTL': 2,
      'hosts': ['192.168.2.123 mymusicbox'],
      'domainNeeded': true,
      'expandHosts': true,
      'domain': 'lan',
      'bogusPriv': true,
      'dnssec': true,
      'interface': 'eth0',
      'hostRecord': '',
      'listeningMode': 'local',
      'queryLogging': false,
      'cnameRecords': [
        '*.example.com,default.example.com',
        'hourly.yetanother.com,yetanother.com,3600',
      ],
      'port': 53,
      'cache': {'size': 10000, 'optimizer': 3600, 'upstreamBlockedTTL': 86400},
      'revServers': ['true,192.168.0.0/24,192.168.0.1,lan'],
      'blocking': {'active': true, 'mode': 'NULL', 'edns': 'NONE'},
      'specialDomains': {
        'mozillaCanary': true,
        'iCloudPrivateRelay': true,
        'designatedResolver': true,
      },
      'reply': {
        'host': {
          'force4': false,
          'force6': false,
          'IPv4': '0.0.0.0',
          'IPv6': '::',
        },
        'blocking': {
          'force4': false,
          'force6': false,
          'IPv4': '0.0.0.0',
          'IPv6': '::',
        },
      },
      'rateLimit': {'count': 0, 'interval': 0},
    },
    'dhcp': {
      'active': false,
      'start': '192.168.0.10',
      'end': '192.168.0.250',
      'router': '192.168.0.1',
      'netmask': '0.0.0.0',
      'leaseTime': '24h',
      'ipv6': false,
      'rapidCommit': false,
      'multiDNS': false,
      'logging': false,
      'ignoreUnknownClients': false,
      'hosts': [
        '11:22:33:44:55:66,192.168.1.123',
        '11:22:33:44:55:67,192.168.1.124,hostname',
      ],
    },
    'ntp': {
      'ipv4': {'active': true, 'address': ''},
      'ipv6': {'active': true, 'address': ''},
      'sync': {
        'active': true,
        'server': 'pool.ntp.org',
        'interval': 3600,
        'count': 8,
        'rtc': {'set': true, 'device': '', 'utc': true},
      },
    },
    'resolver': {
      'resolveIPv4': true,
      'resolveIPv6': true,
      'networkNames': true,
      'refreshNames': 'IPV4_ONLY',
    },
    'database': {
      'DBimport': true,
      'maxDBdays': 365,
      'DBinterval': 60,
      'useWAL': true,
      'network': {'parseARPcache': true, 'expire': 365},
    },
    'webserver': {
      'domain': 'pi.hole',
      'acl': '+0.0.0.0/0,::/0',
      'port': '80,[::]:80',
      'threads': 0,
      'headers': [
        'X-DNS-Prefetch-Control: off',
        "Content-Security-Policy: default-src 'self' 'unsafe-inline';",
        'X-Frame-Options: DENY',
        'X-XSS-Protection: 0',
        'X-Content-Type-Options: nosniff',
        'Referrer-Policy: strict-origin-when-cross-origin',
      ],
      'serve_all': false,
      'session': {'timeout': 300, 'restore': true},
      'tls': {'cert': '/etc/pihole/tls.pem'},
      'paths': {'webroot': '/var/www/html', 'webhome': '/admin/', 'prefix': ''},
      'interface': {'boxed': true, 'theme': 'default-darker'},
      'api': {
        'max_sessions': 16,
        'prettyJSON': false,
        'password': '********',
        'pwhash': '',
        'totp_secret': '',
        'app_pwhash': '',
        'app_sudo': false,
        'cli_pw': true,
        'excludeClients': [r'1\.2\.3\.4', 'localhost', 'fe80::345'],
        'excludeDomains': [r'google\\.de', r'pi-hole\.net'],
        'maxHistory': 86400,
        'maxClients': 10,
        'client_history_global_max': true,
        'allow_destructive': true,
        'temp': {'limit': 60, 'unit': 'C'},
      },
    },
    'files': {
      'pid': '/run/pihole-FTL.pid',
      'database': '/etc/pihole/pihole-FTL.db',
      'gravity': '/etc/pihole/gravity.db',
      'gravity_tmp': '/tmp',
      'macvendor': '/etc/pihole/macvendor.db',
      'pcap': '',
      'log': {
        'ftl': '/var/log/pihole/FTL.log',
        'dnsmasq': '/var/log/pihole/pihole.log',
        'webserver': '/var/log/pihole/webserver.log',
      },
    },
    'misc': {
      'nice': -10,
      'delay_startup': 10,
      'addr2line': true,
      'privacylevel': 0,
      'etc_dnsmasq_d': false,
      'dnsmasq_lines': [],
      'extraLogging': false,
      'readOnly': false,
      'check': {'load': true, 'shmem': 90, 'disk': 90},
    },
    'debug': {
      'database': false,
      'networking': false,
      'locks': false,
      'queries': false,
      'flags': false,
      'shmem': false,
      'gc': false,
      'arp': false,
      'regex': false,
      'api': false,
      'tls': false,
      'overtime': false,
      'status': false,
      'caps': false,
      'dnssec': false,
      'vectors': false,
      'resolver': false,
      'edns0': false,
      'clients': false,
      'aliasclients': false,
      'events': false,
      'helper': false,
      'config': false,
      'inotify': false,
      'webserver': false,
      'extra': false,
      'reserved': false,
      'ntp': false,
      'netlink': false,
      'all': false,
    },
  },
  'took': 0.003,
};

const kSrvGetConfigElement = srv.Config(
  config: srv.ConfigData(dns: srv.Dns(queryLogging: true)),
  took: 0.003,
);

final kSrvPatchConfig = srv.Config.fromJson(kSrvJsonConfigData);

const kRepoFetchDnsQueryLogging = repo.Config(
  dns: repo.Dns(queryLogging: true),
);

const kRepoSetDnsQueryLogging = repo.Config(dns: repo.Dns(queryLogging: false));
