import 'package:pi_hole_client/config/enums.dart';
import 'package:pi_hole_client/data/model/v6/network/devices.dart' as srv;
import 'package:pi_hole_client/data/model/v6/network/gateway.dart' as srv;
import 'package:pi_hole_client/data/model/v6/network/interfaces.dart' as srv;
import 'package:pi_hole_client/data/model/v6/network/routes.dart' as srv;
import 'package:pi_hole_client/domain/model/network/network.dart' as repo;

const kSrvGetNetworkDevices = srv.Devices(
  devices: [
    srv.DeviceData(
      id: 1,
      hwaddr: '00:11:22:33:44:55',
      interface: 'enp2s0',
      firstSeen: 1664623620,
      lastQuery: 1664688620,
      numQueries: 585462,
      macVendor: 'Digital Data Communications Asia Co.,Ltd',
      ips: [
        srv.DeviceIp(
          ip: '192.168.1.51',
          name: 'ubuntu-server',
          lastSeen: 1664688620,
          nameUpdated: 1664688620,
        ),
      ],
    ),
    srv.DeviceData(
      id: 2,
      hwaddr: '00:11:22:33:44:xx',
      interface: 'enp2s0',
      firstSeen: 1664523620,
      lastQuery: 1664588620,
      numQueries: 562,
      ips: [
        srv.DeviceIp(
          ip: '192.168.1.52',
          name: 'ubuntu-server',
          lastSeen: 1664588620,
          nameUpdated: 1654588620,
        ),
        srv.DeviceIp(
          ip: '192.168.1.62',
          lastSeen: 1664488620,
          nameUpdated: 1654488620,
        ),
      ],
    ),
  ],
  took: 0.003,
);

const kSrvGetNetworkGateway = srv.Gateway(
  gateways: [
    srv.GatewayData(
      family: 'inet',
      interface: 'eth0',
      address: '192.168.0.1',
      local: ['192.168.0.22'],
    ),
    srv.GatewayData(
      family: 'inet6',
      interface: 'eth0',
      address: 'fe80::3587:2fff:f11a:1',
      local: ['fe80::3587:2fff:f11a:4321'],
    ),
  ],
  took: 0.003,
);

const kSrvGetNetworkGatewayDetailed = srv.Gateway(
  gateways: [
    srv.GatewayData(
      family: 'inet',
      interface: 'eth0',
      address: '192.168.0.1',
      local: ['192.168.0.22'],
    ),
  ],
  interfaces: [
    srv.InterfaceData(
      name: 'eth0',
      index: 2,
      family: 'unspec',
      speed: 1000,
      type: 'ether',
      flags: ['up', 'broadcast', 'running'],
      ifname: 'eth0',
      txqlen: 1000,
      state: 'up',
      linkmode: 0,
      mtu: 1500,
      minMtu: 68,
      maxMtu: 1500,
      group: 0,
      promiscuity: 0,
      unknown: [61, 58],
      numTxQueues: 5,
      gsoMaxSegs: 65535,
      gsoMaxSize: 65536,
      numRxQueues: 5,
      carrier: true,
      carrierChanges: 5,
      carrierUpCount: 3,
      carrierDownCount: 2,
      protoDown: false,
      address: 'f4:5e:02:ca:ef:e1',
      broadcast: 'ff:ff:ff:ff:ff:ff',
      permAddress: 'f4:5e:02:ca:ef:e1',
      qdisc: 'mq',
      map: 0,
      stats: srv.InterfaceStats(
        rxBytes: srv.ByteValue(value: 1047.89, unit: 'M'),
        txBytes: srv.ByteValue(value: 679.96, unit: 'M'),
        bits: 64,
        rxPackets: 4104288,
        txPackets: 3271447,
        rxErrors: 0,
        txErrors: 0,
        rxDropped: 0,
        txDropped: 11,
        multicast: 326302,
        collisions: 0,
        rxLengthErrors: 0,
        rxOverErrors: 0,
        rxCrcErrors: 0,
        rxFrameErrors: 0,
        rxFifoErrors: 0,
        rxMissedErrors: 0,
        txAbortedErrors: 0,
        txCarrierErrors: 0,
        txFifoErrors: 0,
        txHeartbeatErrors: 0,
        txWindowErrors: 0,
        rxCompressed: 0,
        txCompressed: 0,
        rxNohandler: 0,
      ),
      addresses: [
        srv.InterfaceAddress(
          index: 2,
          family: 'inet',
          scope: 'universe',
          flags: ['permanent'],
          prefixlen: 24,
          address: '192.168.0.22',
          addressType: 'private',
          local: '192.168.0.22',
          localType: 'private',
          broadcast: '192.168.0.255',
          broadcastType: 'private',
          label: 'eth0',
          prefered: 4294967295,
          valid: 4294967295,
          cstamp: 1745897378.81,
          tstamp: 1745897378.81,
        ),
      ],
    ),
  ],
  routes: [
    srv.RouteData(
      table: 254,
      family: 'inet',
      protocol: 'boot',
      scope: 'universe',
      type: 'unicast',
      flags: ['onlink'],
      iflags: 4,
      gateway: '192.168.0.1',
      oif: 'eth0',
      dst: 'default',
    ),
    srv.RouteData(
      table: 254,
      family: 'inet',
      protocol: 'kernel',
      scope: 'link',
      type: 'unicast',
      flags: [],
      iflags: 0,
      dst: '192.168.0.0',
      prefsrc: '192.168.0.22',
      oif: 'eth0',
    ),
  ],
  took: 0.003,
);

// repo models
final kRepoFetchDevices = [
  repo.Device(
    id: 1,
    hwaddr: '00:11:22:33:44:55',
    interface: 'enp2s0',
    firstSeen: DateTime.fromMillisecondsSinceEpoch(1664623620 * 1000),
    lastQuery: DateTime.fromMillisecondsSinceEpoch(1664688620 * 1000),
    numQueries: 585462,
    macVendor: 'Digital Data Communications Asia Co.,Ltd',
    ips: [
      repo.DeviceIp(
        ip: '192.168.1.51',
        name: 'ubuntu-server',
        lastSeen: DateTime.fromMillisecondsSinceEpoch(1664688620 * 1000),
        nameUpdated: DateTime.fromMillisecondsSinceEpoch(1664688620 * 1000),
      ),
    ],
  ),
  repo.Device(
    id: 2,
    hwaddr: '00:11:22:33:44:xx',
    interface: 'enp2s0',
    firstSeen: DateTime.fromMillisecondsSinceEpoch(1664523620 * 1000),
    lastQuery: DateTime.fromMillisecondsSinceEpoch(1664588620 * 1000),
    numQueries: 562,
    ips: [
      repo.DeviceIp(
        ip: '192.168.1.52',
        name: 'ubuntu-server',
        lastSeen: DateTime.fromMillisecondsSinceEpoch(1664588620 * 1000),
        nameUpdated: DateTime.fromMillisecondsSinceEpoch(1654588620 * 1000),
      ),
      repo.DeviceIp(
        ip: '192.168.1.62',
        lastSeen: DateTime.fromMillisecondsSinceEpoch(1664488620 * 1000),
        nameUpdated: DateTime.fromMillisecondsSinceEpoch(1654488620 * 1000),
      ),
    ],
  ),
];

const kRepoFetchGateways = repo.Gateways(
  gateways: [
    repo.Gateway(
      family: 'inet',
      interface: 'eth0',
      address: '192.168.0.1',
      local: ['192.168.0.22'],
    ),
    repo.Gateway(
      family: 'inet6',
      interface: 'eth0',
      address: 'fe80::3587:2fff:f11a:1',
      local: ['fe80::3587:2fff:f11a:4321'],
    ),
  ],
);

const repo.Gateways kRepoFetchGatewaysDetailed = repo.Gateways(
  gateways: [
    repo.Gateway(
      family: 'inet',
      interface: 'eth0',
      address: '192.168.0.1',
      local: ['192.168.0.22'],
    ),
  ],
  interfaces: [
    repo.NetInterface(
      name: 'eth0',
      type: 'ether',
      flags: ['up', 'broadcast', 'running'],
      state: 'up',
      protoDown: false,
      address: 'f4:5e:02:ca:ef:e1',
      broadcast: 'ff:ff:ff:ff:ff:ff',
      stats: repo.InterfaceStats(
        rxBytes: repo.ByteValue(value: 1047.89, unit: 'M'),
        txBytes: repo.ByteValue(value: 679.96, unit: 'M'),
        bits: 64,
        rxPackets: 4104288,
        txPackets: 3271447,
        rxErrors: 0,
        txErrors: 0,
        rxDropped: 0,
        txDropped: 11,
        multicast: 326302,
        collisions: 0,
        rxLengthErrors: 0,
        rxOverErrors: 0,
        rxCrcErrors: 0,
        rxFrameErrors: 0,
        rxFifoErrors: 0,
        rxMissedErrors: 0,
        txAbortedErrors: 0,
        txCarrierErrors: 0,
        txFifoErrors: 0,
        txHeartbeatErrors: 0,
        txWindowErrors: 0,
        rxCompressed: 0,
        txCompressed: 0,
        rxNohandler: 0,
      ),
      addresses: [
        repo.InterfaceAddress(
          index: 2,
          family: RouteFamilyType.inet,
          scope: 'universe',
          flags: ['permanent'],
          prefixlen: 24,
          address: '192.168.0.22',
          addressType: 'private',
          local: '192.168.0.22',
          localType: 'private',
          broadcast: '192.168.0.255',
          broadcastType: 'private',
          label: 'eth0',
          prefered: 4294967295,
          valid: 4294967295,
          cstamp: 1745897378.81,
          tstamp: 1745897378.81,
        ),
      ],
      index: 2,
      family: 'unspec',
      speed: 1000,
      permAddress: 'f4:5e:02:ca:ef:e1',
      ifname: 'eth0',
      txqlen: 1000,
      linkmode: 0,
      mtu: 1500,
      minMtu: 68,
      maxMtu: 1500,
      group: 0,
      promiscuity: 0,
      unknown: [61, 58],
      numTxQueues: 5,
      numRxQueues: 5,
      gsoMaxSegs: 65535,
      gsoMaxSize: 65536,
      carrier: true,
      carrierChanges: 5,
      carrierUpCount: 3,
      carrierDownCount: 2,
      map: 0,
      qdisc: 'mq',
    ),
  ],
  routes: [
    repo.Route(
      table: 254,
      family: RouteFamilyType.inet,
      protocol: 'boot',
      scope: 'universe',
      type: 'unicast',
      flags: ['onlink'],
      dst: 'default',
      iflags: 4,
      gateway: '192.168.0.1',
      oif: 'eth0',
    ),
    repo.Route(
      table: 254,
      family: RouteFamilyType.inet,
      protocol: 'kernel',
      scope: 'link',
      type: 'unicast',
      flags: [],
      iflags: 0,
      dst: '192.168.0.0',
      prefsrc: '192.168.0.22',
      oif: 'eth0',
    ),
  ],
);
