name: Deploy static content to Pages

on:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Prepare artifact
        run: |
          mkdir -p _site
          cp website/404.html _site/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: _site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5b