name: Manual Build Windows Installer

on:
  workflow_dispatch:

jobs:
  get-version:
    name: Extract Version from pubspec.yaml
    runs-on: ubuntu-latest
    outputs:
      VERSION_NAME: ${{ steps.extract_version.outputs.VERSION_NAME }}
      VERSION_NUMBER: ${{ steps.extract_version.outputs.VERSION_NUMBER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          VERSION_FULL=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          VERSION_NAME=$(echo $VERSION_FULL | cut -d '+' -f 1)
          VERSION_NUMBER=$(echo $VERSION_FULL | cut -d '+' -f 2)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_OUTPUT
          echo "Extracted Version Name: $VERSION_NAME"
          echo "Extracted Version Number: $VERSION_NUMBER"

  build-windows:
    name: Build Windows installer
    runs-on: windows-latest
    needs: get-version
    env:
      VERSION_NAME: ${{ needs.get-version.outputs.VERSION_NAME }}
      VERSION_NUMBER: ${{ needs.get-version.outputs.VERSION_NUMBER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode .env
        shell: pwsh
        run: |
          [IO.File]::WriteAllBytes('.env', [Convert]::FromBase64String('${{ secrets.ENV }}'))

      - name: Update version in innosetup config file
        shell: pwsh
        run: |
          (Get-Content windows/innosetup_installer_builder.iss) -replace '<REPLACE_VERSION_ACTIONS>', '${{ env.VERSION_NAME }}' | Out-File -encoding ASCII windows/innosetup_installer_builder.iss

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version: 3.29.1
      - run: flutter clean
      - run: flutter pub get

      - name: Build windows
        run: flutter build windows --release

      - name: Build installer witn innosetup
        run: iscc /Q windows/innosetup_installer_builder.iss

      - name: Rename installer
        shell: pwsh
        run: Move-Item -Path build/windows/PiHoleClient.exe -Destination build/windows/PiHoleClient_${{ env.VERSION_NAME }}_Windows_x64.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows/PiHoleClient_${{ env.VERSION_NAME }}_Windows_x64.exe

    name: Release Android build to the Google Play Store
    runs-on: ubuntu-latest
    needs: [get-version, build-android, build-linux, build-windows]
    permissions:
      contents: read
      id-token: write
    env:
      VERSION_NAME: ${{ needs.get-version.outputs.VERSION_NAME }}
      VERSION_NUMBER: ${{ needs.get-version.outputs.VERSION_NUMBER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Android artifacts
        uses: actions/download-artifact@v4
        with:
          name: android

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Release app to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: io.github.tsutsu3.pi_hole_client
          releaseFiles: PiHoleClient_${{ env.VERSION_NAME }}_Android.aab
          track: production # Available tracks are: production,beta,alpha,internal,test
          status: draft
          releaseName: ${{ env.VERSION_NAME }}